### ISSUE TITLE
The authToken cannot be passed in when setting the http proxy  

### ISSUE THREAD

**Issue by yxk756** [sashabaranov/go-openai#118]
authToken cannot be passed in when setting http proxy. When setting custom config using NewClientWithConfig(), authToken cannot be set externally because authToken is in lower case. You want to provide a way to set authToken.

**Comment by eryajf** [comment]
You can take a look at my example here.

https://github.com/eryajf/chatgpt-dingtalk/blob/6d4d1df8087e6c661ee4f65b1dc442a7eef6de05/pkg/chatgpt/chatgpt.go#L40-L62

**Comment by yxk756** [comment]
> You can take a look at my example here.
> 
> https://github.com/eryajf/chatgpt-dingtalk/blob/6d4d1df8087e6c661ee4f65b1dc442a7eef6de05/pkg/chatgpt/chatgpt.go#L40-L62

谢谢！

**Comment by vvatanabe** [comment]
I'm closing this because it appears to have already been resolved.
