### ISSUE TITLE
Issue on embedding type

### ISSUE THREAD

**Issue by IANTHEREAL** [sashabaranov/go-openai#132]
The vector embedding type definition used by common vector engines are all []float32, such as [weaviate](https://github.com/weaviate/weaviate-go-client/blob/166fe5a522098db1ff0f2738605f72142995db65/weaviate/graphql/hybridbuilder.go#L23). Would go-openai consider changing `Embedding []float64` to `Embedding []float32`?

**Comment by sashabaranov** [comment]
Just added this in v1.5.0 https://github.com/sashabaranov/go-openai/releases/tag/v1.5.0

thank you for the suggestion!
