### ISSUE TITLE
"https://api.openai.com/v1/chat/completions": x509: certificate

### ISSUE THREAD

**Issue by 905049079** [sashabaranov/go-openai#137]
Post "https://api.openai.com/v1/chat/completions": x509: certificate has expired or is not yet valid

**Comment by nasa1024** [comment]
> Post "https://api.openai.com/v1/chat/completions": x509: certificate has expired or is not yet valid

gfw

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
