### ISSUE TITLE
feature request: Add support for Azure OpenAI Service

### ISSUE THREAD

**Issue by tao12345666333** [sashabaranov/go-openai#142]
As a user of the project, I would like to request the addition of support for Azure OpenAI. This would allow me to leverage the power of the Azure OpenAI platform, which offers cutting-edge AI technologies and services, including natural language processing, speech recognition, and computer vision.

I believe that adding support for Azure OpenAI would greatly enhance the functionality and usefulness of the project, and would be a valuable addition for users who are looking to integrate AI capabilities into their applications.

I look forward to hearing your thoughts on this proposal, and I am happy to provide additional information or assistance as needed. Thank you for considering this request.

https://azure.microsoft.com/en-us/blog/chatgpt-is-now-available-in-azure-openai-service/

Most of the APIs are the same, with only a few differences. refer to: https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference

Something like this needs to be adjusted or made configurable.
https://github.com/sashabaranov/go-openai/blob/9428f6cc3df02488c3ada31cfa7005c4c3d6c027/chat.go#L82

**Comment by AtiqGauri** [comment]
+1 for this, we want to access azure openAI service, this would be a great enhancement to the library.

**Comment by ziyixi** [comment]
Same here. We can also leverage the free credits provided by Azure, which is much more than OpenAI's $18.

**Comment by meixiu** [comment]
When will the Azure open ai API be supported?

**Comment by tao12345666333** [comment]
If no one handles it, I will pick it up. I saw some people gave it a +1, which shows that this feature is practical.

**Comment by ttys3** [comment]
just filed a PR https://github.com/sashabaranov/go-openai/pull/214
