### ISSUE TITLE
Whisper Prompt and Response Format

### ISSUE THREAD

**Issue by jkelly-multivac** [sashabaranov/go-openai#143]
Hey there,
Was looking at the CreateTranscription and noticed there isn't an option to set prompt or response_format. I'll attempt to add locally but wanted to check to see if I'm just missing where that option might already be able to be set. I don't see it conditionally in the form part creation but thought I would check.

**Comment by jkelly-multivac** [comment]
I have this working locally but had to add an alternative sendRequest to api.go also to allow for raw (non JSON) response. Probably not in a good PR state. I feel a little hacky using a different request chain if the response format isn't JSON.

**Comment by hoani** [comment]
This is being addressed here https://github.com/sashabaranov/go-openai/pull/267 - probably quite similar to what you have implemented... but I think this is probably ok given that the API provides a response that is intended to be written directly to file.
