### ISSUE TITLE
GPT-4

### ISSUE THREAD

**Issue by sashabaranov** [sashabaranov/go-openai#154]
> To get access to the GPT-4 API (which uses the same [ChatCompletions API](https://platform.openai.com/docs/guides/chat/chat-vs-completions) as gpt-3.5-turbo), please [sign up for our waitlist](https://openai.com/waitlist/gpt-4). We will start inviting some developers today, and scale up gradually to balance capacity with demand. If you are a researcher studying the societal impact of AI or AI alignment issues, you can also apply for subsidized access via our [Researcher Access Program](https://share.hsforms.com/1b-BEAq_qQpKcfFGKwwuhxA4sk30).

https://openai.com/research/gpt-4

**Comment by go-dockly** [comment]
https://platform.openai.com/docs/models/gpt-4

it's available. cap of 100 messages every 4 hours

**Comment by sashabaranov** [comment]
Partially covered in https://github.com/sashabaranov/go-openai/pull/157

**Comment by jordon31** [comment]
@sashabaranov  You put it but not yet implemented properly 

i get this 

"currently, only gpt-3.5-turbo and gpt-3.5-turbo-0301 are supported"

**Comment by sashabaranov** [comment]
@jordon31 @cccdz please re-try after updating the library v1.5.2 fixes that.

```
go get -u github.com/sashabaranov/go-openai
```

**Comment by cccdz** [comment]
@sashabaranov 
<img width="615" alt="image" src="https://user-images.githubusercontent.com/45749908/225538487-944cdc59-6cf1-4b4c-b208-d2d004bbdded.png">

**Comment by sashabaranov** [comment]
@cccdz the GPT-4 API is invitation-only now, did you get the invitation?

**Comment by cccdz** [comment]
understand

> @cccdz the GPT-4 API is invitation-only now, did you get the invitation?
