### ISSUE TITLE
streaming data

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-openai#164]
hi , does the latest version still not support streaming data

**Comment by sashabaranov** [comment]
it does support streaming, please see the README

**Comment by imsprojo2fan** [comment]
> it does support streaming, please see the README

I mean chatgpt support stram?

**Comment by sashabaranov** [comment]
Yes, https://github.com/sashabaranov/go-openai/blob/a8acb5f63bcb4d5966d1a57709a32315eeff1ff9/chat_stream_test.go#L53

**Comment by imsprojo2fan** [comment]
> Yes,here's an example in the test
> 
> https://github.com/sashabaranov/go-openai/blob/a8acb5f63bcb4d5966d1a57709a32315eeff1ff9/chat_stream_test.go#L53

fine,thank you
