### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-openai#165]
why it always return 'invalid character '<' looking for beginning of value'

**Comment by imsprojo2fan** [comment]
nginx time out

**Comment by devstein** [comment]
@imsprojo2fan I occasionally run into this as well. Is this a timeout on OpenAI's side?

**Comment by imsprojo2fan** [comment]
> @imsprojo2fan I occasionally run into this as well. Is this a timeout on OpenAI's side?

Maybe，The problem I encountered was that the domain name of the transit connection timed out. It is normal to set the timeout period of nginx to 180 seconds
