### ISSUE TITLE
ChatCompletionRequest with stream: true return EOF

### ISSUE THREAD

**Issue by yuluyao** [sashabaranov/go-openai#173]
When using ChatCompletionRequest and setting `stream: true` to send multiple conversation content, EOF is returned and no error information can be obtained.

**Comment by sashabaranov** [comment]
@yuluyao Hey, please use the [CreateChatCompletionStream](https://pkg.go.dev/github.com/sashabaranov/go-openai#Client.CreateChatCompletionStream) call. We should error out in case `Stream: true` is passed to non-stream calls like `CreateChatCompletion` or `CreateCompletion`.

**Comment by hcws** [comment]
when I use CreateChatCompletionStream ， when ，meet 
1. You exceeded your current quota
2. That model is currently overloaded with other requests
3. This model's maximum context length is...
the stream return EOF , it maybe not good , it should return the error reason @sashabaranov

**Comment by sashabaranov** [comment]
@hcws could you please elaborate on how API returns that to you? Does that happen via server-sent events?

**Comment by hcws** [comment]
In [chat_stream.go]( https://github.com/sashabaranov/go-openai/blob/master/chat_stream.go)
`waitForData:
	line, err := stream.reader.ReadBytes('\n')
	if err != nil {
		return
	}

	var headerData = []byte("data: ")
	line = bytes.TrimSpace(line)
	if !bytes.HasPrefix(line, headerData) {
		emptyMessagesCount++
		if emptyMessagesCount > stream.emptyMessagesLimit {
			err = ErrTooManyEmptyStreamMessages
			return
		}

		goto waitForData
	}

	line = bytes.TrimPrefix(line, headerData)
	if string(line) == "[DONE]" {
		stream.isFinished = true  # **when opensi server return errors like use out of money  line equal "[DONE]"** 
		err = io.EOF                     #  **but err return the errors ,we should return err not EOF**
		return
	}

	err = json.Unmarshal(line, &response)
	return`

**Comment by sashabaranov** [comment]
With the token you've provided and the following patch:

```diff
diff --git a/chat_stream.go b/chat_stream.go
index 26e964c..0371554 100644
--- a/chat_stream.go
+++ b/chat_stream.go
@@ -6,6 +6,7 @@ import (
        "context"
        "encoding/json"
        "io"
+       "log"
        "net/http"
 )

@@ -39,6 +40,7 @@ type ChatCompletionStream struct {

 func (stream *ChatCompletionStream) Recv() (response ChatCompletionStreamResponse, err error) {
        if stream.isFinished {
+               log.Print("Stream finished")
                err = io.EOF
                return
        }
@@ -48,9 +50,12 @@ func (stream *ChatCompletionStream) Recv() (response ChatCompletionStreamRespons
 waitForData:
        line, err := stream.reader.ReadBytes('\n')
        if err != nil {
+               log.Printf("Returning error: %v", err)
                return
        }

+       log.Printf("line: %s", string(line))
+
        var headerData = []byte("data: ")
        line = bytes.TrimSpace(line)
        if !bytes.HasPrefix(line, headerData) {
@@ -65,6 +70,7 @@ waitForData:

        line = bytes.TrimPrefix(line, headerData)
        if string(line) == "[DONE]" {
+               log.Print("Stream [DONE]")
                stream.isFinished = true
                err = io.EOF
                return
```


I've got the following result:

```
2023/03/18 20:21:14 line: {
2023/03/18 20:21:14 line:     "error": {
2023/03/18 20:21:14 line:         "message": "Incorrect API key provided: sk-Ymoxa***************************************mvYO. You can find your API key at https://platform.openai.com/account/api-keys.",
2023/03/18 20:21:14 line:         "type": "invalid_request_error",
2023/03/18 20:21:14 line:         "param": null,
2023/03/18 20:21:14 line:         "code": "invalid_api_key"
2023/03/18 20:21:14 line:     }
2023/03/18 20:21:14 line: }
2023/03/18 20:21:14 Returning error: EOF
```

So it seems that error is returned line-by-line

**Comment by liushuangls** [comment]
> With the token you've provided and the following patch:
> 
> ```diff
> diff --git a/chat_stream.go b/chat_stream.go
> index 26e964c..0371554 100644
> --- a/chat_stream.go
> +++ b/chat_stream.go
> @@ -6,6 +6,7 @@ import (
>         "context"
>         "encoding/json"
>         "io"
> +       "log"
>         "net/http"
>  )
> 
> @@ -39,6 +40,7 @@ type ChatCompletionStream struct {
> 
>  func (stream *ChatCompletionStream) Recv() (response ChatCompletionStreamResponse, err error) {
>         if stream.isFinished {
> +               log.Print("Stream finished")
>                 err = io.EOF
>                 return
>         }
> @@ -48,9 +50,12 @@ func (stream *ChatCompletionStream) Recv() (response ChatCompletionStreamRespons
>  waitForData:
>         line, err := stream.reader.ReadBytes('\n')
>         if err != nil {
> +               log.Printf("Returning error: %v", err)
>                 return
>         }
> 
> +       log.Printf("line: %s", string(line))
> +
>         var headerData = []byte("data: ")
>         line = bytes.TrimSpace(line)
>         if !bytes.HasPrefix(line, headerData) {
> @@ -65,6 +70,7 @@ waitForData:
> 
>         line = bytes.TrimPrefix(line, headerData)
>         if string(line) == "[DONE]" {
> +               log.Print("Stream [DONE]")
>                 stream.isFinished = true
>                 err = io.EOF
>                 return
> ```
> 
> I've got the following result:
> 
> ```
> 2023/03/18 20:21:14 line: {
> 2023/03/18 20:21:14 line:     "error": {
> 2023/03/18 20:21:14 line:         "message": "Incorrect API key provided: sk-Ymoxa***************************************mvYO. You can find your API key at https://platform.openai.com/account/api-keys.",
> 2023/03/18 20:21:14 line:         "type": "invalid_request_error",
> 2023/03/18 20:21:14 line:         "param": null,
> 2023/03/18 20:21:14 line:         "code": "invalid_api_key"
> 2023/03/18 20:21:14 line:     }
> 2023/03/18 20:21:14 line: }
> 2023/03/18 20:21:14 Returning error: EOF
> ```
> 
> So it seems that error is returned line-by-line

How to solve this problem

**Comment by batmac** [comment]
I have a similar problem since v1.5.3:

I used to detect api errors (for instance, bad api key) with this:
`	stream, err := client.CreateChatCompletionStream(ctx, req)
        // (...)
	if stream.GetResponse().StatusCode != http.StatusOK  {
		return 0, errors.New(stream.GetResponse().Status)
	}
`
but since v1.5.3 GetResponse() no longer exists. 
What is the recommended way to get the error now please? For now the stream just returns EOF but I haven't found a way to get the error status.

**Comment by hcws** [comment]
![image](https://user-images.githubusercontent.com/28213814/226266869-9f0c1518-525a-45c9-ad6e-cf6a10689d5f.png)
is there any developer who can help me review the method

**Comment by sashabaranov** [comment]
@hcws thank you for working on this! A couple of suggestions:

* Please use [bytes.Buffer](https://pkg.go.dev/bytes#Buffer) instead of `Errorbytes []byte`
* The `isRevData` variable is not really needed, we can just accumulate outputs that don't match `data: ` or `[DONE]` into a buffer, and then try to `json.Unmarshal` it into [APIError](https://github.com/sashabaranov/go-openai/blob/d529d13ba15d31928a414f83f9ae9730d0a9223b/error.go#L6) struct. In case the unmarshalling succeeds, we can wrap this error with [fmt.Errorf](https://github.com/sashabaranov/go-openai/blob/d529d13ba15d31928a414f83f9ae9730d0a9223b/api.go#L70)
