### ISSUE TITLE
The audio file cannot be deleted after calling Speech-To-Text API

### ISSUE THREAD

**Issue by MichaelWangGitHub2** [sashabaranov/go-openai#175]
After calling the Audio Speech-To-Text API, the audio file cannot be deleted and a message appears indicating that it is being used.
![delvoice](https://user-images.githubusercontent.com/30011094/226167897-5b9ff5d7-e9d0-43d3-ac5a-2972f2ad4619.png)

**Comment by elisongomes** [comment]
The fix was merged into master.
