### ISSUE TITLE
Could not find a method to actively destroy the connection

### ISSUE THREAD

**Issue by Meng-Xin** [sashabaranov/go-openai#176]
I can't find a way to destroy the link I created with the NewClientWithConfig function. How long does this link exist by default? What would be the problem if created infinitely?

**Comment by Meng-Xin** [comment]
At present, when I am building http.transport{}, it is controlled by IdleConnTimeout.
http.transport.go
>	IdleConnTimeout time.Duration

**Comment by sashabaranov** [comment]
@Meng-Xin, the library does not keep alive any connections during the lifetime of the `Client`. The connections are made only when you do API calls. Streaming calls like `CreateChatCompletionStream` and `CreateCompletionStream` create streams that keep an open connection, but they also have the `Close()` method to close the connection.

I hope that helps!

**Comment by Meng-Xin** [comment]
learned, thanks
