### ISSUE TITLE
feature request: add retry and timeout mecanism for api calls

### ISSUE THREAD

**Issue by LeslieLeung** [sashabaranov/go-openai#181]
Sometimes the chat completion api might be slow, so a retry and timeout mechanism might come in handy.

**Comment by lucky777strike** [comment]
+

**Comment by merore** [comment]
I think timeout mechanism is sufficient, retry is not needed.

**Comment by Meng-Xin** [comment]
You can configure the http.transport

**Comment by sashabaranov** [comment]
There are already multiple ways to achieve timeout/retry:

* `context.WithTimeout` https://golang.cafe/blog/golang-context-with-timeout-example.html
* Set timeout `HTTPClient` in [ClientConfig](https://pkg.go.dev/github.com/sashabaranov/go-openai#ClientConfig) like this: https://stackoverflow.com/questions/16895294/how-to-set-timeout-for-http-get-requests-in-golang
* For retries you can use https://github.com/avast/retry-go
