### ISSUE TITLE
conversation history

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-openai#187]
Hi, Is there a sample code for context calls that can record the full conversation

**Comment by sashabaranov** [comment]
@imsprojo2fan please check the last example in the README

**Comment by imsprojo2fan** [comment]
> @imsprojo2fan please check the last example in the README

And how to prevent the token from being too long

**Comment by vvatanabe** [comment]
@imsprojo2fan With the OpenAI API, you can limit the number of tokens returned by setting the max_tokens parameter. 


> And how to prevent the token from being too long

**Comment by vvatanabe** [comment]
This issue will be closed due to inactivity.
