### ISSUE TITLE
Invalid input image - format must be in ['RGBA', 'LA', 'L'], got RGB.

### ISSUE THREAD

**Issue by kimberw** [sashabaranov/go-openai#188]
1. use CreateImage get a url or a base64 image
2. save it at local, use `io.Copy`
3. use this local image as CreateEditImage's input 

failed, return Invalid input image - format must be in ['RGBA', 'LA', 'L'], got RGB.

**Comment by vvatanabe** [comment]
@kimberw Please check here:
https://community.openai.com/t/how-can-i-provide-a-rgba-png-file-to-openai-php-library/22604/3

**Comment by vvatanabe** [comment]
This issue will be closed due to inactivity.
