### ISSUE TITLE
Remote service always return EOF

### ISSUE THREAD

**Issue by goldkyo** [sashabaranov/go-openai#189]
I'm trying to fetch a response from remote chatGPT service with following code:
```
func Chat3(msg string) string {
	c := openai.NewClient("my token")
	ctx := context.Background()

	req := openai.CompletionRequest{
		Model:     openai.GPT3Ada,
		MaxTokens: 5,
		Prompt:    msg,
	}
	resp, err := c.CreateCompletion(ctx, req)
	if err != nil {
		fmt.Printf("Completion error: %v\n", err)
		return ""
	}
	fmt.Println(resp.Choices[0].Text)
	return resp.Choices[0].Text
}
```

But the code above always gives me an error:
Completion error: Post "https://api.openai.com/v1/completions": EOF

Any idea about it? Thank you.

**Comment by linabellbiu** [comment]
我也遇到了

**Comment by goldkyo** [comment]
@rexposadas Sorry for the late update, I found out that the root cause of the issue is in my network environment. Just miss leaded by that EOF, which makes me considering about a data error. Thank you for helping.

**Comment by rexposadas** [comment]
@goldkyo Sounds good. We can probably close this issue.

**Comment by goldkyo** [comment]
Yes, sure. Done, thank you.

**Comment by Derek-yzh** [comment]
@goldkyo 
What environmental issue caused you to get that EOF?
