### ISSUE TITLE
Incomplete about the stream

### ISSUE THREAD

**Issue by yzchen27** [sashabaranov/go-openai#193]
The content of each request and response is incomplete. How to solve this problem

**Comment by sashabaranov** [comment]
@yzchen27 could you elaborate with a concrete example, please?

**Comment by yzchen27** [comment]
all requests forward using nginx . I use the homepage GPT-3 streaming completion example, Content is “Please write a short composition about AI in Chinese” (The same goes for Englished ). change the http request  timeout, but it didn't work.
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/65482191/227148783-4c56983c-ea05-43ae-9f8b-c911c40550ec.png">

**Comment by yzchen27** [comment]
I did not have this problem using Okhttp3 in Java

**Comment by stephen9412** [comment]
我也遇到了這個問題

**Comment by stephen9412** [comment]
I also encountered this problem.

**Comment by dragonforce2010** [comment]
Mee too

**Comment by abu2202** [comment]
Has anyone solved this probelm?
