### ISSUE TITLE
Reset Dialog Context

### ISSUE THREAD

**Issue by JackBekket** [sashabaranov/go-openai#198]
I m looking to way to reset current dialog context with ChatGPT

I've found a way to do it using openAI Python library

```
response = openai.Completion.create(
    engine="davinci",
    prompt="Hello, how are you?",
    temperature=0.5,
    max_tokens=50,
    reset=True  # This allow to drop dialog context and start over
)
```

Is it a way to do it with this library?

**Comment by rahulkoul123** [comment]
I would like to claim this issue. Will resolve it soon.
