### ISSUE TITLE
Ability to count tokens before sending

### ISSUE THREAD

**Issue by AndrewMohawk** [sashabaranov/go-openai#200]
Reading the Open AI docs on [Chat completion](https://platform.openai.com/docs/guides/chat/managing-tokens) they specifically call out counting tokens on input (as you are billed on these as well as the amount of tokens on output). They use their TikToken python library, it would be awesome if there was something in this lib to do the same

**Comment by sashabaranov** [comment]
Related: #62

**Comment by sashabaranov** [comment]
I think this library should solve this, right? github.com/pkoukk/tiktoken-go

**Comment by allesan** [comment]
Can you give example how one would use this library that you have linked?
Because ChatCompletionMessage.Content accepts string, not []uint

**Comment by sashabaranov** [comment]
@allesan tiktoken-go library might be used to count tokens, but not to pass them to ChatCompletionMessage

**Comment by allesan** [comment]
Is there some library or a way to send tokens with go-openai?

**Comment by sashabaranov** [comment]
@allesan what do you mean? You _are_ sending tokens, just packed in the string representation (i.e. just a prompt string).

**Comment by allesan** [comment]
But if I understand correctly, with tiktoken lib you are sending tokens that are shortend and optimized for openai models?

**Comment by sashabaranov** [comment]
@allesan OpenAI API does not allow you to send tokenized inputs to it, see the API documentation: https://platform.openai.com/docs/api-reference/introduction


tiktoken lets you tokenize your inputs to count the number of tokens or use these tokens to train your own models.

**Comment by qhenkart** [comment]
@allesan  tiktoken-go does resolve this problem for me. Now I can effectively maximize the tokens in the request by setting

MaxTokens: MaxAllowedTokens - countTokens(systemPrompt+assistantPrompt+userPrompt),

where count tokens is just a copy and paste of the example in tiktoken

```
func countTokens(prompt string) int {
	encoding := "cl100k_base"

	tke, err := tiktoken.GetEncoding(encoding)
	if err != nil {
		panic(err)
	}

	return len(tke.Encode(prompt, nil, nil))
}

```

@sashabaranov I would love to see this as a feature of this library instead of having to pull in another third party. Would you accept a PR?

**Comment by vvatanabe** [comment]
If there's more to discuss, please post it in issue #62.
