### ISSUE TITLE
请问请求体中的role字段有什么实际用途

### ISSUE THREAD

**Issue by zhuqiming** [sashabaranov/go-openai#203]
// Chat message role defined by the OpenAI API.
const (
	ChatMessageRoleSystem    = "system"
	ChatMessageRoleUser      = "user"
	ChatMessageRoleAssistant = "assistant"
)
请教下，这三个角色的含义是什么？

**Comment by nekomeowww** [comment]
According to the [official guide](https://platform.openai.com/docs/guides/chat):

> The system message helps set the behavior of the assistant. In the example above, the assistant was instructed with "You are a helpful assistant." *Note: [gpt-3.5-turbo-0301](https://platform.openai.com/docs/models) does not always pay strong attention to system messages. Future models will be trained to pay stronger attention to system messages.*

> The user messages help instruct the assistant. They can be generated by the end users of an application, or set by a developer as an instruction.

> The assistant messages help store prior responses. They can also be written by a developer to help give examples of desired behavior.

In Simplified Chinese:

> 系统消息有助于设置助手的行为。在上面的例子中，助手被指导为“您是一个有帮助的助手”。注：[gpt-3.5-turbo-0301](https://platform.openai.com/docs/models)并不总是强调注意系统消息。未来的模型将被训练以更加关注系统消息。

> 用户消息有助于指导助手。它们可以由应用程序的最终用户生成，也可以由开发人员设置为指令。

> 助手消息有助于存储之前的响应。它们也可以由开发人员编写以帮助提供所需行为的示例。

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
