### ISSUE TITLE
How to check errors returned by `CreateChatCompletion` was a network or rate limiting issues ?

### ISSUE THREAD

**Issue by guoqiangqi** [sashabaranov/go-openai#207]
I am retring my request with the exponential backoff when encountering network or rate limiting issues. Currently, it seems that `go-openai` does not provide specific network errors for requests by `client.CreateChatCompletion` and other,  `openai python client` do a good job by providing errors like `openai.error.RateLimitError, openai.error.APIError, openai.error.Timeout, openai.error.APIConnectionError, openai.error.ServiceUnavailableError`, how can i check errors returned by `CreateChatCompletion` was a network or rate limiting issues ?

**Comment by dannysievers** [comment]
This can be solved by using `errors.As()` as seen in the example README. Check out PR comments #293 for implementation details.
```
e := &openai.APIError{}
if errors.As(err, &e) {
  switch e.HTTPStatusCode {
    case 401:
      // invalid auth or key (do not retry)
    case 429:
      // rate limiting or engine overload (wait and retry) 
    case 500:
      // openai server error (retry)
    default:
      // unhandled
  }
}
```

**Comment by guoqiangqi** [comment]
@dannysievers it works, thanks for your code!
