### ISSUE TITLE
EOF

### ISSUE THREAD

**Issue by imsprojo2fan** [sashabaranov/go-openai#208]
Hi，why this error return EOF
`"message": "This model's maximum context length is 4097 tokens. However, your messages resulted in 4153 tokens. Please reduce the length of the messages."`

**Comment by vvatanabe** [comment]
@imsprojo2fan In the OpenAI API, there is a limit on the total number of tokens for prompts and completions in a single API interaction. The limit varies depending on the model. Please see https://platform.openai.com/docs/models
