### ISSUE TITLE
CreateChatCompletionStream接口stream返回时，并不是真的流式返回，日志显示都是在同一秒

### ISSUE THREAD

**Issue by holbos-deng** [sashabaranov/go-openai#218]
config := openai.DefaultConfig(openai_key)
	config.BaseURL = BaseURL
	c := openai.NewClientWithConfig(config)
	ctx := context.Background()

	req := openai.ChatCompletionRequest{
		Model:     openai.GPT3Dot5Turbo,
		MaxTokens: 800,
		Messages: []openai.ChatCompletionMessage{
			{
				Role:    openai.ChatMessageRoleUser,
				Content: "写一篇800字的短文",
			},
		},
		Stream: true,
	}
	stream, err := c.CreateChatCompletionStream(ctx, req)
	if err != nil {
		fmt.Printf("ChatCompletionStream error: %v\n", err)
		return
	}
	defer stream.Close()

	fmt.Printf("Stream response: ")
	for {
		response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			fmt.Println("Stream finished")
			return
		}

		if err != nil {
			fmt.Println("Stream error: ", err)
			return
		}

		fmt.Println("消息：", time.Now().Format(time.DateTime), response.Choices[0].Delta.Content)
	}

**Comment by pluveto** [comment]
Same issue

**Comment by pluveto** [comment]
I resolved it. In my case I write a custom http transport, and this transport collected response until finish, so the recv didn't work. Just use the default transport.

**Comment by zhengyansheng** [comment]
如何停止正在运行 生成答案的流呢？

**Comment by coolmingwu** [comment]
> I resolved it. In my case I write a custom http transport, and this transport collected response until finish, so the recv didn't work. Just use the default transport.

能看下你的解决方法吗

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
