### ISSUE TITLE
Model GPT-4: The model: `gpt-4` does not exist

### ISSUE THREAD

**Issue by itsahedge** [sashabaranov/go-openai#219]
go-openai v1.5.7

I'm wondering why specifying GPT-4 as the Model returns an error indicating it does not exist? 

This is taken from the example, but changes the model to use GPT-4.

```
error: The model: `gpt-4` does not exist
```

```go
resp, err := g.openAi.CreateChatCompletion(
		ctx,
		openai.ChatCompletionRequest{
			Model: openai.GPT4,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: "Hello!",
				},
			},
		},
	)
```

**Comment by kotaroyamazaki** [comment]
me too.

Do you have access to the GPT4 API?
Seems like you would need to register and be authorized on waitlist.
https://openai.com/waitlist/gpt-4-api
<img width="808" alt="image" src="https://user-images.githubusercontent.com/7589567/229339085-a718f450-7649-4204-9615-a423fc1c0aab.png">

On another matter.
It seems strange that this response error is a 404, but it seems to be a problem on the openai side, not the library side

**Comment by itsahedge** [comment]
> me too.
> 
> Do you have access to the GPT4 API? Seems like you would need to register and be authorized on waitlist. https://openai.com/waitlist/gpt-4-api <img alt="image" width="808" src="https://user-images.githubusercontent.com/7589567/229339085-a718f450-7649-4204-9615-a423fc1c0aab.png">
> 
> On another matter. It seems strange that this response error is a 404, but it seems to be a problem on the openai side, not the library side

Yes I have access to GPT4 already with my OpenAI account. I can currently use GPT-4 in the normal ChatGPT interface.

**Comment by sashabaranov** [comment]
@itsahedge As far as I understand, ChatGPT interface access ≠ API access. I've got an email inviting me to try GPT4 and the exact same usage with `Model: openai.GPT4` works for me.

**Comment by oliverbenns** [comment]
It seems GPT 4 is now enabled for all api users who have a history of successful payments: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4

However I still do not seem to have access, it might be because even though I have billing enabled, I still am under their free tier.
