### ISSUE TITLE
syntax error: unexpected

### ISSUE THREAD

**Issue by suifengqjn** [sashabaranov/go-openai#225]
run demo 

../../../github.com/sashabaranov/go-openai/chat_stream.go:29:15: syntax error: unexpected [, expecting semicolon or newline or }
../../../github.com/sashabaranov/go-openai/stream.go:14:15: syntax error: unexpected [, expecting semicolon or newline or }
../../../github.com/sashabaranov/go-openai/stream_reader.go:12:31: syntax error: unexpected |, expecting semicolon or newline or }
../../../github.com/sashabaranov/go-openai/stream_reader.go:15:21: syntax error: unexpected streamable, expecting ]
../../../github.com/sashabaranov/go-openai/stream_reader.go:25:27: syntax error: unexpected [, expecting comma or )
../../../github.com/sashabaranov/go-openai/stream_reader.go:33:1: syntax error: non-declaration statement outside function body
../../../github.com/sashabaranov/go-openai/stream_reader.go:44:2: syntax error: non-declaration statement outside function body
../../../github.com/sashabaranov/go-openai/stream_reader.go:70:27: syntax error: unexpected [, expecting comma or )

**Comment by suifengqjn** [comment]
fixed

**Comment by jetBn** [comment]
how to fixed?
