### ISSUE TITLE
chat history 

### ISSUE THREAD

**Issue by ahmedRSA** [sashabaranov/go-openai#228]
has anyone created a project that saves history to some db ?
and use data as context

**Comment by ahmedRSA** [comment]
maybe something like this? 
this way we will never hit 4000 token limit
![image](https://user-images.githubusercontent.com/77731877/230291918-747dcb70-1fb0-4b40-a66c-050e7f765d73.png)

**Comment by Jose082** [comment]
In python there's a way to accomplish that with [NLTK](https://blog.devgenius.io/how-to-get-around-openai-gpt-3-token-limits-b11583691b32#:~:text=OpenAI%20GPT%2D3%20is%20limited,i.e.%2C%20prompt)%20and%20response.), not sure in GO.

**Comment by agrogov** [comment]
@ahmedRSA If you don't need to keep all history, then you can create array of requests and responses `historyList []openai.ChatCompletionMessage` and append it each time you sending request to `CreateChatCompletion()`, then after you got a response, in `response.Usage.TotalTokens` you'll see number of tokens spend for current request+response.
Based on this data you can create `trimHistoryList()` function to trim head of the array based on your conditions.

**Comment by taricov** [comment]
why don't u connect to a db and write token/s on every input submission to the logged-in user document (non SQL)?

**Comment by jhonroxton** [comment]
> @ahmedRS how to chat based on history, after logout, user login again, I want them to be able to continue the discussion based on their previous conversation history. use previous data as context.
