### ISSUE TITLE
如何获取 花费的 token 数？

### ISSUE THREAD

**Issue by tangwenru** [sashabaranov/go-openai#231]
```
stream, errCreate := gptClient.CreateChatCompletionStream(ctx, reqData)

response, err := stream.Recv() 
```

### 问题：
为什么 1.6.1 取消了 response.Usage 对象？
也就是说，现在 无法得知 返回内容 花费的 token 了。。

有什么办法 得知么？

**Comment by fsmytsai** [comment]
我有一樣的問題，有人能回覆嗎？

**Comment by smile-magic** [comment]
#223

**Comment by yyyyzwd** [comment]
俺也一样

**Comment by nasa1024** [comment]
当stream = true时，接口不会返回tokenNum，需要用户自己去计算
@tangwenru @yyyyzwd @smile-magic @fsmytsai 
可以参考 [#223](https://github.com/sashabaranov/go-openai/pull/223)的方式
或者直接使用 [tiktoken-go](https://github.com/pkoukk/tiktoken-go)

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period. Hopefully, the proposed solution has resolved your issue.

**Comment by vvatanabe** [comment]
Related: #62
