### ISSUE TITLE
How to achieve that in the same session, the results of two identical request parameters cannot be the same

### ISSUE THREAD

**Issue by timepasser-by** [sashabaranov/go-openai#232]
How to do it? Calling this interface twice with the same request parameters ensures that the results obtained are inconsistent. For example, in the same session, sending the same question content twice will result in different answers

**Comment by timepasser-by** [comment]
Seek help from all the powerful leaders regarding this issue

**Comment by vvatanabe** [comment]
@timepasser-by  Please see https://github.com/sashabaranov/go-openai/issues/9

**Comment by vvatanabe** [comment]
This is a duplicate issue with #9, so please discuss it in #9 from now on.
