### ISSUE TITLE
[ERR] invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by salman0ansari** [sashabaranov/go-openai#233]
```go
client := openai.NewClient("KEY")
gptResponse, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT3Dot5Turbo,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: prompt,
				},
			},
		},
	)

if err != nil {
	fmt.Println(err) // invalid character '<' looking for beginning of value
	return
}
```

**Comment by alex-ello** [comment]
Can you show an example of a prompt that would cause this error?

**Comment by salman0ansari** [comment]
> Can you show an example of a prompt that would cause this error?

This error is random, today i got this error when i used this prompt "status meaning".

**Comment by Prayforhanluo** [comment]
use proxy , this err appear

**Comment by alex-ello** [comment]
It looks like the response is not a valid JSON, and this error can be solved at the library level.

**Comment by leobuzhi** [comment]
This is because your baseURL is not properly set with a suffix. The correct format should be http://YOUR_DOMAIN:YOUR_PORT/v1. It's possible that you forgot to include 'v1'.
@Prayforhanluo @lollipopkit

**Comment by lollipopkit** [comment]
> This is because your baseURL is not properly set with a suffix. The correct format should be http://YOUR_DOMAIN:YOUR_PORT/v1. It's possible that you forgot to include 'v1'.
> @Prayforhanluo @lollipopkit 

But this error only occurs occasionally, so it should not be a problem with baseurl.

Maybe my situation is different from everyone else's, maybe it's a network problem.

Thank you for your reply.

**Comment by salman0ansari** [comment]
> This is because your baseURL is not properly set with a suffix. The correct format should be http://YOUR_DOMAIN:YOUR_PORT/v1. It's possible that you forgot to include 'v1'. @Prayforhanluo @lollipopkit

this doesn't fix this error.

**Comment by katcipis** [comment]
> The error still occurs when no proxy is used.
> 
> > use proxy , this err appear

I'm using no proxy and I get the same error, also randomly, there is no specific prompt that seems to trigger it (there is no way to debug the exact response from OpenAI, but it seems that it is not a JSON since it fails on the JSON decoder).

**Comment by lollipopkit** [comment]
> > The error still occurs when no proxy is used.
> > 
> > > use proxy , this err appear
> 
> I'm using no proxy and I get the same error, also randomly, there is no specific prompt that seems to trigger it (there is no way to debug the exact response from OpenAI, but it seems that it is not a JSON since it fails on the JSON decoder).

I think so too, it feels like the JSON parser is inputting the XML

**Comment by imsprojo2fan** [comment]
If you use nginx, you can set the timeout to be longer. I encountered this problem earlier because the mapped address request openai interface timed out

**Comment by stricklandye** [comment]
> This is because your baseURL is not properly set with a suffix. The correct format should be http://YOUR_DOMAIN:YOUR_PORT/v1. It's possible that you forgot to include 'v1'. @Prayforhanluo @lollipopkit

it works for me,Thanks.

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.

**Comment by guoqingxibei** [comment]
In my case, it seems that this error will be thrown if the wait time exceeds 100s, should we fix it internally?
