### ISSUE TITLE
The Input type and limitations in EmbeddingRequest need to be updated

### ISSUE THREAD

**Issue by vinsec** [sashabaranov/go-openai#240]
In the latest documentation for the OpenAI Embedding create API, the input can not only be a string type but also a slice of tokenized tokens. [The original text](https://platform.openai.com/docs/api-reference/embeddings/create#embeddings/create-input) is as follows:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/22928057/230767830-d86de6b9-b8ea-4ecc-973e-4a40203db1c5.png">

Moreover, more importantly, the input token limit is 8192 instead of 2048 in go-openai.

So, the structure of this section and the comments in it may need to be modified.

https://github.com/sashabaranov/go-openai/blob/334ee6dbddabfceb3b76146fc5b38c19426a9551/embeddings.go#L117

**Comment by vvatanabe** [comment]
@vinsec Fixed: #417

@jacksors Thanks!
