### ISSUE TITLE
no usage available when using CreateChatCompletionStream

### ISSUE THREAD

**Issue by xoba** [sashabaranov/go-openai#254]
whereas `ChatCompletionResponse` has a `Usage` field where i can see how many tokens were involved in a request, there is nothing like that for `ChatCompletionStream`. since i need to monitor usage, this is a problem for me. so i would request that usage is somehow provided for streaming requests. on the other hand, i heard that such information is not even provided by openai, which would be unfortunate. thanks!

**Comment by sashabaranov** [comment]
The OpenAI API does not return usage when streaming, see #223 

You can try using https://github.com/pkoukk/tiktoken-go to count tokens, see #200
