### ISSUE TITLE
BaseURL不可以自定义

### ISSUE THREAD

**Issue by ZeroDeng01** [sashabaranov/go-openai#261]
你好，希望可以接受用户自己传入的BaseURL，因为某些原因，部分地区的用户访问不了[https://api.openai.com](https://api.openai.com)，需要用户传入一个反向代理后的自定义地址。我记得1.7.0版本用户在配置参数的时候可以通过如下方式修改BaseURL：
config := openai.DefaultConfig(OpenAiKey)
config.BaseURL = OpenAiBaseURL

**Comment by ZeroDeng01** [comment]
我自己处理有点问题，已经解决了

**Comment by HuXinjing** [comment]
> 我自己处理有点问题，已经解决了

请问怎么解决的
