### ISSUE TITLE
whisper openai.AudioRequest.FilePath

### ISSUE THREAD

**Issue by xoba** [sashabaranov/go-openai#265]
i would like to create whisper model transcriptions from audio in a memory-based buffer, ideally of type `[]byte`; whereas currently the only way to identify audio in this sdk is via `openai.AudioRequest.FilePath`, thus it must be stored in the underlying OS's filesystem.

in my current use case, the audio file is already in a `[]byte` buffer, never came from a filesystem in the first place, thus it feels unnecessary and artificial to explicitly store it in a temporary file and thereafter delete it in order to use whisper api via this projects sdk.

thanks!

**Comment by vvatanabe** [comment]
@xoba Done #331
