### ISSUE TITLE
费流量

### ISSUE THREAD

**Issue by betawu2000** [sashabaranov/go-openai#271]
非常费流量如何结局呢

**Comment by nasa1024** [comment]
你是觉得使用`stream`模式消耗的token数量多吗？主开发者是外国人，他应该看不到，想要更快的得到回复，please use english.
@betawu2000

**Comment by nasa1024** [comment]
@sashabaranov  You can close this issue because betawu2000 not reply.

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
