### ISSUE TITLE
syntax error: unexpected |, expecting semicolon or newline or }

### ISSUE THREAD

**Issue by Winston1011** [sashabaranov/go-openai#273]
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/chat_stream.go:30:15: syntax error: unexpected [, expecting semicolon or newline or }
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream.go:15:15: syntax error: unexpected [, expecting semicolon or newline or }
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:12:31: syntax error: unexpected |, expecting semicolon or newline or }
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:15:21: syntax error: unexpected streamable, expecting ]
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:25:27: syntax error: unexpected [, expecting comma or )
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:33:1: syntax error: non-declaration statement outside function body
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:44:2: syntax error: non-declaration statement outside function body
../localGoPath/pkg/mod/github.com/sashabaranov/go-openai@v1.9.0/stream_reader.go:70:27: syntax error: unexpected [, expecting comma or )

**Comment by vvatanabe** [comment]
@Winston1011 Perhaps your locally installed version of Go is less than 1.18. go-openai uses generics internally, so Go 1.18 or higher is required.

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
