### ISSUE TITLE
Stripping whitespace makes it difficult to format streamed content

### ISSUE THREAD

**Issue by dannysievers** [sashabaranov/go-openai#276]
Hello, is there any reason that the output from the stream completion needs to strip the whitespace?

It makes it very difficult to accurately format the streamed content if you are attempting to create a "chat-like" experience with this package. Any suggestions on how to improve the formatting of the streamed output would be much appreciated if I'm missing something!

The code I am talking about can be found [here](https://github.com/sashabaranov/go-openai/blob/2f008f7054b2651f45e5e0e1bc1858c1359f803b/stream_reader.go#L44).

**Comment by dannysievers** [comment]
Upon looking further into the issue. It seems like the referenced code is not the cause of stripping white space in the response chunks. Does anyone know why the content returned from a chat stream does not include white space for formatting streaming responses?

**Comment by shibingli** [comment]
I'm currently facing this problem too, are there any solutions available?

**Comment by dannysievers** [comment]
Hey @vsumit89 - I saw you post an issue about streaming chat completion (#284). Do you happen to have any input on this issue? If you are having success formatting streamed chat outputs, any advice would be much appreciated!

**Comment by vsumit89** [comment]
Hi @dannysievers, I am not sure whether this will help you, here's my experience. I am getting markdown content from the chatgpt api and streaming it to a component I have for rendering markdown. Initially I rendered whatever output I got from chatgpt, but it didn't work because of bad formatting. So what I did was I got the data and marshalled it into a struct and then the data seemed to rendered properly for me.

**Comment by shibingli** [comment]
@vsumit89  May I ask which component you are using to render Markdown? I found during my debugging of the code that the data returned by Stream does indeed remove some whitespace from strings.

**Comment by vsumit89** [comment]
Hi @shibingli  I am using react-markdown.

**Comment by shibingli** [comment]
@vsumit89    Thank you. I am using Vue 3 and Markdown-it on my end, and I've noticed that the formatting for code is not very user-friendly.

**Comment by mrold** [comment]
@shibingli 假设你用的是**ChatGPT streaming completion**， 假设你直接返回的content的内容`fmt.Printf(response.Choices[0].Delta.Content)` ，  你必须在前端js代码中执行JSON.parse()

**Comment by shibingli** [comment]
@mrold     response.Choices[0].Delta.Content 取出来的数据，已经是去除白字符的了吧？另外，我在吐到前端前，用的是一个结构体，然后编码成json。前端在接收到 data时，就是用的 JSON.parse，Markdown格式依然乱，就是因为数据的前后空白都去除了。

**Comment by mrold** [comment]
@shibingli 建议检查一下你的前端代码，比如css属性`white-space`。也可以看看这个库有没有帮助：https://github.com/remarkjs/remark-breaks。 或你把json数据发我一份，我本地试试!

**Comment by shibingli** [comment]
> @shibingli 建议检查一下你的前端代码，比如css属性`white-space`。也可以看看这个库有没有帮助：[https://github.com/remarkjs/remark-breaks。](https://github.com/remarkjs/remark-breaks%E3%80%82) 或你把json数据发我一份，我本地试试!

感谢，我去试试。我这边用的流式请求。

**Comment by shibingli** [comment]
@mrold   已解决，非常感谢。发现是前端的样式问题，后端调用数据处理这块也有点问题，调整了一下，都处理了好了。

**Comment by mrold** [comment]
@shibingli  不客气
