### ISSUE TITLE
Azure OpenAI list models

### ISSUE THREAD

**Issue by jsburckhardt** [sashabaranov/go-openai#287]
## What 

When using the api to list models `client.ListModels` the end point doesn't use the AzureConfigDefault but the Default one, making the fullURL non existent.

## Expected behaviour

- if the APIType is Azure I would expect to get a list of models available.

## Current behaviour

- receiving an 404 (wrong endpoint and wrong api)

## Support links

- the end point for listing models in Azure OpenAI is [link](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/azureopenaistable/models/list?tabs=HTTP)

**Comment by vvatanabe** [comment]
Fixed #290
