### ISSUE TITLE
How to get openai api result status code ?

### ISSUE THREAD

**Issue by jiriyao** [sashabaranov/go-openai#288]
(How to get openai api result status code )
ChatGPT error 401: {
"error": {
"message": "Incorrect API key provided: sk-bwInV***************************************pk3i. You can find your API key at https://platform.openai.com/account/api-keys.",
"type": "invalid_request_error",
"param": null,
"code": "invalid_api_key"
}
}

how to get  resp.StatusCode for logic ? thanks.

**Comment by jiriyao** [comment]
not surpport it ?

**Comment by vvatanabe** [comment]
@jiriyao Instructions on how to check status codes are provided in the README.

```go
e := &openai.APIError{}
if errors.As(err, &e) {
  switch e.HTTPStatusCode {
    case 401:
      // invalid auth or key (do not retry)
    case 429:
      // rate limiting or engine overload (wait and retry) 
    case 500:
      // openai server error (retry)
    default:
      // unhandled
  }
}
```
Refs: https://github.com/sashabaranov/go-openai#other-examples
