### ISSUE TITLE
v1.9.1 check sum mismatched in sum.golang.org

### ISSUE THREAD

**Issue by Kitaministrator** [sashabaranov/go-openai#295]
Platform: Windows 10 21H2
Go version: go1.20.3 windows/amd64

When I run `go get github.com/sashabaranov/go-openai`, I got error messages:
```
go: downloading github.com/sashabaranov/go-openai v1.9.1
go: github.com/sashabaranov/go-openai@v1.9.1: verifying module: checksum mismatch
        downloaded: h1:mxaX3YEKz2EqQzUWXNLgF7HSEs6QZUh0ZaVPxClUIFk=
        sum.golang.org: h1:3N52HkJKo9Zlo/oe1AVv5ZkCOny0ra58/ACvAxkN3MM=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.
```

I think there's something wrong between the v1.9.1 released version and sum.golang.org.
By running `go get github.com/sashabaranov/go-openai@v1.9.0`, it went successfully.

**Comment by sashabaranov** [comment]
@Kitaministrator thank you for reporting! This release was scrapped and then re-released shortly. The v1.9.2 is up https://github.com/sashabaranov/go-openai/releases/tag/v1.9.2

**Comment by vvatanabe** [comment]
Closing this due to lack of comments for an extended period.
