### ISSUE TITLE
`APIError` is suggested to be returned from `stream.Recv()`

### ISSUE THREAD

**Issue by hophacker** [sashabaranov/go-openai#302]
In the example below, it is very helpful to get `err type` other than err message at some cases. For example, when your quota exceeded, the raw response is 
```json
{
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": null
    }
}
```
This error will be returned by `stream.Recv()` and the error message is generated as `error, You exceeded your current quota, please check your plan and billing details."`. Error message is changeable due to many reasons, thus it is imprecise to determine that the account has no quota through it. Instead, `error type` is needed here since it is supposed to be hard to change.

So, an error object to return is needed here, a.k.a, `APIError` is suggested to be returned from `stream.Recv()`

```golang
		stream, err := tunnel.OpenaiClient.CreateChatCompletionStream(cc, req)
		if err != nil {
			return err
		}
		defer stream.Close()

		for {
			response, err := stream.Recv()
			if errors.Is(err, io.EOF) {
				fmt.Println("\nStream finished")
				return nil
			}

			if err != nil {
				return err
			}
			w.Write([]byte(response.Choices[0].Delta.Content))
			w.(http.Flusher).Flush()
		}
	}
```

**Comment by hophacker** [comment]
never mind, I found a way to to that
```golang
func getErrType(err error) string {
	unwrappedError := errors.Unwrap(err)
	if unwrappedError != nil {
		if apiErr, ok := unwrappedError.(*openai.APIError); ok {
			return apiErr.Type
		}
	}
	return ""
}
```

**Comment by dannysievers** [comment]
This can be solved by using `errors.As()` as seen in the example README. Check out PR comments #293 for implementation details.
```
e := &openai.APIError{}
if errors.As(err, &e) {
  switch e.HTTPStatusCode {
    case 401:
      // invalid auth or key (do not retry)
    case 429:
      // rate limiting or engine overload (wait and retry) 
    case 500:
      // openai server error (retry)
    default:
      // unhandled
  }
}
```

**Comment by vvatanabe** [comment]
I'm closing this because it appears to have already been resolved.
