### ISSUE TITLE
Feature Request: Add support for retrieving all uploaded files and querying fine-tuned models  

### ISSUE THREAD

**Issue by emoob** [sashabaranov/go-openai#315]
I hope this message finds you well. I have been using your "gozhong" package for integrating with the OpenAI API, and I am impressed with its functionality. I wanted to reach out to suggest a feature enhancement and seek guidance on a related topic.

- Feature Request: Retrieving all uploaded files
  I would like to propose adding support for retrieving all uploaded files from the OpenAI API. Currently, it seems that the package lacks the functionality to fetch a list of all files uploaded by the user. According to the OpenAI API documentation, the /v1/files endpoint allows users to list their uploaded files by making a GET request to the following URL: https://api.openai.com/v1/files. Integrating this functionality into the "gozhong" package would greatly improve the user experience and enable better management and monitoring of uploaded files. Additionally, it would be beneficial to have the ability to retrieve specific file information such as ID, name, and other metadata.

- Querying fine-tuned models
Another aspect I would like to discuss is the usage of fine-tuned models. It would be helpful if the package could provide guidance or examples on how to use fine-tuned models in conjunction with the OpenAI API. Specifically, I am interested in understanding the recommended approach for utilizing my own fine-tuned models in the requests made through the "gozhong" package. Any insights or code snippets demonstrating this integration would be greatly appreciated.

I believe that incorporating these features into the "gozhong" package would significantly enhance its usability and value to the community. I understand that implementing these changes may require additional effort, but I believe they would greatly benefit users like myself who rely on your package for OpenAI integration.

Thank you for your time and consideration. I look forward to your response and any insights you can provide regarding these suggestions.

**Comment by vvatanabe** [comment]
@emoob 
> Feature Request: Retrieving all uploaded files

Implemented https://github.com/sashabaranov/go-openai/pull/348

**Comment by vvatanabe** [comment]
> Querying fine-tuned models

Would anyone be able to write some clear sample code for the example/ directory or in the README?

**Comment by mehulgohil** [comment]
@vvatanabe I can help here to provide example for usage of fine tune

**Comment by vvatanabe** [comment]
@emoob Added an example of fine tune model in #438.
