### ISSUE TITLE
ChatCompletion error: error, status code: 404, message: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

### ISSUE THREAD

**Issue by poweredbyai** [sashabaranov/go-openai#323]
Azure OpenAI ChatGPT

ChatCompletion error: error, status code: 404, message: The API deployment for this resource does not exist. If you created the deployment within the last 5 minutes, please wait a moment and try again.

**Comment by sashabaranov** [comment]
@poweredbyai what's the name of your deployment?

**Comment by wj4832** [comment]
> @poweredbyai what's the name of your deployment?

same question.when my version is v1.9.3,it's ok, but v1.9.5 will not work.my name of deployment is gpt-35-turbo-0301.
by the way, my work way is stream

**Comment by fregie** [comment]
I met the same issue.
I set the api version to `2023-03-15-preview` and it works.(I found this api version in Azure AI Studio -> Chat playgrount -> Chat session -> view Code)
Change code like this:
```go
config := openai.DefaultAzureConfig(apiKey, azureEndpoint)
config.APIVersion = "2023-03-15-preview"
```

**Comment by fregie** [comment]
@sashabaranov 
It seems that `apiVersion` need to configure before use,it is not a constant value.
I found python sample code in azure openai chat playgrount:
```python
openai.api_type = "azure"
openai.api_base = "https://fob-openai-chatbot.openai.azure.com/"
openai.api_version = "2023-03-15-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
```
I can create a pull request to fix this issue.
We can add a variadic parameters to `DefaultAzureConfig`,to ensure that is compatible with previous versions.Like this:
```golang
config := openai.DefaultAzureConfig(apiKey, azureEndpoint, openai.WithApiVersion("2023-03-15-preview"))
```

**Comment by tsubasaxZZZ** [comment]
I also saw you shareI'm facing the same error even though set API version.
I believe name of model and deployment name is correct, but if you are aware of something to fix, I would like your advice.
```golang
	config := openai.DefaultAzureConfig(os.Getenv("AOAI_KEY"), os.Getenv("AOAI_ENDPOINT"))
	config.APIVersion = "2023-03-15-preview"
	config.AzureModelMapperFunc = func(model string) string {
		modelmapper := map[string]string{
			"gpt-3.5-turbo-16k-0613": "tsunomur-gpt-35-turb-16k",
		}
		if val, ok := modelmapper[model]; ok {
			return val
		}
		return model
	}
```

**Comment by krisice** [comment]
I met the same error, who can solve it?

**Comment by tsubasaxZZZ** [comment]
I realised that I had to correct the following part at the same time:
```golang
resp, err := client.CreateChatCompletion(
context.Background(),
openai.ChatCompletionRequest{
	Model: openai.GPT3Dot5Turbo16K0613, <---------------------- change to this
	Messages: []openai.ChatCompletionMessage{
		{
		
```
