### ISSUE TITLE
Temperature param being ignored?

### ISSUE THREAD

**Issue by rishsriv** [sashabaranov/go-openai#333]
Hi there! Thank you for maintaining this package. It has made our lives so much simpler.

I wanted to check if the temperature parameter is somehow being ignored in the library?

We have an implementation that is something like this
```
resp, err := Openai.CreateChatCompletion(
	c,
	openai.ChatCompletionRequest{
		Model:       "gpt-3.5-turbo",
		Messages:    messages,
		MaxTokens:   600,
		Temperature: 0.0,
		Stop:        []string{"```"},
	},
)
```

But this is ignoring the temperature parameter and returning a different response every time. This issue does not seem to be present when using the Python library or making a CURL request to the OpenAI API.

**Comment by vvatanabe** [comment]
@rishsriv @sashabaranov I investigated the cause of the problem.
https://github.com/sashabaranov/go-openai/pull/334#issue-1735004506

**Comment by rishsriv** [comment]
Thank you so much for investigating this, @vvatanabe !

**Comment by vvatanabe** [comment]
Duplicate https://github.com/sashabaranov/go-openai/issues/9

**Comment by vvatanabe** [comment]
This is a duplicate issue with https://github.com/sashabaranov/go-openai/issues/9, so please discuss it in https://github.com/sashabaranov/go-openai/issues/9 from now on.
