### ISSUE TITLE
The error handling function handleErrorResp cannot match *openai.APIError

### ISSUE THREAD

**Issue by icowan** [sashabaranov/go-openai#337]
POST /v1/chat/completions HTTP/1.1
Accept: text/event-stream
Authorization: Bearer
Cache-Control: no-cache
Connection: keep-alive
Content-Type: application/json

{"model":"vicuna-7b-v1.1","messages":[{"role":"user","content":"hello"}],"max_tokens":512,"temperature":0.9,"top_p":0.7,"stream":true}
HTTP/1.1 400 Bad Request
Content-Length: 103
Connection: keep-alive
Content-Type: application/json
Date: Fri, 02 Jun 2023 02:28:38 GMT
Server: openresty

{"object":"error","message":"Only vicuna-13b-v1.1 allowed now, your model vicuna-7b-v1.1","code":40301}

<img width="952" alt="image" src="https://github.com/sashabaranov/go-openai/assets/6229526/6556e37a-5bd2-4e72-acce-3fd07e010eaa">

<img width="539" alt="image" src="https://github.com/sashabaranov/go-openai/assets/6229526/b2ba1ea3-e07f-4722-bc58-f3c84af4490c">

The errRes.Error in this place will always be nil, because there is no error field in resp.Body

**Comment by vvatanabe** [comment]
@icowan The OpenAI API error response has the following format. Your error response format seems to be different.

```
{
    "error": {
        "message": "Human-readable error message",
        "type": "OpenAI error type, for example "invalid_request_error"",
        "param": null,
        "code": null
    }
}
```

Perhaps there is a proxy server in between? My `Server` header in the OpenAI API response is `cloudflare`. But your `Server` header  is `openresty`.

**Comment by icowan** [comment]
> 

Yes, the server is FastChat.  https://github.com/lm-sys/FastChat

**Comment by icowan** [comment]
> 

Okay, shall I try using another solution for compatibility! Thank you for your patient explanation.
