### ISSUE TITLE
go

### ISSUE THREAD

**Issue by SimpleKris** [sashabaranov/go-openai#358]

**Comment by SimpleKris** [comment]
when i use command go get github.com/sashabaranov/go-openai, the following error happened: 

go: ctgithub.com/json-iterator/go@v1.1.12: unrecognized import path "ctgithub.com/json-iterator/go": https fetch: Get "https://ctgithub.com/json-iterator/go?go-get=1": dial tcp: lookup ctgithub.com: no such host

so what is the reason?

**Comment by vvatanabe** [comment]
@SimpleKris 
`shabaranov/go-openai` does not depend on any other library. `sashabaranov/go-openai` does not seem to be the cause.

Refs(does not depends):
https://github.com/sashabaranov/go-openai/blob/master/go.mod

I found one strange URL in your comment.
`ctgithub.com/json-iterator/go` is incorrect.
`github.com/json-iterator/go` is correct.

**Comment by SimpleKris** [comment]
Thanks！I solve it.
