### ISSUE TITLE
I wanna add some Timeout to client but it seem like unavailable, how can I complete it? 

### ISSUE THREAD

**Issue by Cristo-R** [sashabaranov/go-openai#370]
If I replace the custom ClientConfig then my auto token cann't inject it, is there some solution?

**Comment by vvatanabe** [comment]
@Cristo-R For example:
```go
cfg := openai.DefaultConfig("openai_api_key")
cfg.BaseURL = "custom_base_url"
cfg.OrgID = "custom_org_id"
cfg.HTTPClient = &http.Client{} // <= add a custom http client 
cfg.EmptyMessagesLimit = 9999
```

**Comment by Cristo-R** [comment]
> @Cristo-R For example:
> 
> ```go
> cfg := openai.DefaultConfig("openai_api_key")
> cfg.BaseURL = "custom_base_url"
> cfg.OrgID = "custom_org_id"
> cfg.HTTPClient = &http.Client{} // <= add a custom http client 
> cfg.EmptyMessagesLimit = 9999
> ```

My fault! I haven't fount the **DefaultConfig** method. I just code like openapi.DefaultConfig{}. I got it , tks very much!
