### ISSUE TITLE
ChatCompletionRequest.FunctionCall does not support specific functions

### ISSUE THREAD

**Issue by chrikoch** [sashabaranov/go-openai#378]
Setting ChatCompletionRequest.FunctionCall to "auto" or "none" is no problem at all, but the OpenAI API will reject the request when using a specific function.

When using this:

```
FunctionCall: `{"name": "getWeather"}`,
```

it is sent like this "on the wire":

```
"function_call":"{\"name\": \"getWeather\"}
```
Obviously "FunctionCall" is intepreted as a string (as it is one), but not as a JSON object. Correct would be this:
```
"function_call":{"name": "getWeather"}
```

**Comment by zbysir** [comment]
This issue will fixed in the PR: 
https://github.com/sashabaranov/go-openai/pull/374

Just wait a while.

**Comment by MrCher55** [comment]
Could you please provide some examples for the Function call part where we are calling our own specific functions within the OpenAI API?
https://platform.openai.com/docs/guides/gpt/function-calling

**Comment by vvatanabe** [comment]
@MrCher55 Your question is beyond the scope of this issue. Could you possibly create a new issue or ask in the [discussions](https://github.com/sashabaranov/go-openai/discussions)?

**Comment by vvatanabe** [comment]
Already fixed #https://github.com/sashabaranov/go-openai/pull/374
