### ISSUE TITLE
Add a method to query the remaining tokens of key

### ISSUE THREAD

**Issue by gouguoyin** [sashabaranov/go-openai#380]
Add a method to query the total and remaining tokens of key

**Comment by anhao** [comment]
https://github.com/pkoukk/tiktoken-go

**Comment by vvatanabe** [comment]
FYI
> If it would be possible to bring tokenization with zero (or minimal) dependencies — I'm all for merging it. Otherwise, I think it makes sense to implement it in a separate repo.

https://github.com/sashabaranov/go-openai/issues/62#issuecomment-1423777601

**Comment by kamushadenes** [comment]
I used https://github.com/j178/tiktoken-go (Rust bindings), replaced with pure-Go https://github.com/pkoukk/tiktoken-go with no issued at all.

**Comment by vvatanabe** [comment]
If there's more to discuss, please post it in issue #62.
