### ISSUE TITLE
Stream object have no Close method and Recv method

### ISSUE THREAD

**Issue by qxdo** [sashabaranov/go-openai#386]
<img width="1095" alt="image" src="https://github.com/sashabaranov/go-openai/assets/13347187/1c05b81e-389b-4fa4-93fc-daffdf3afad1">
Hi, I want to run the ChatGPT stream demo, but the code shows the stream object have no Close method and Recv method,that's the README.md ChatGPT code, my Go version is 1.20.3.

**Comment by qxdo** [comment]
I've tried  remove the Golang package download in the `~/go/pkg/github.com/sashabaranov`, and retry the `go get github.com/sashabaranov/go-openai` and that error is still.

**Comment by qxdo** [comment]
I tried this code, It could run. but is there anything wrong?

**Comment by kamushadenes** [comment]
Since the code ran, this is a problem with your IDE. Try to find some option to reindex your code.

**Comment by qxdo** [comment]
thank you very much, I've fix this issue.
