### ISSUE TITLE
Can you customize the API address? Some regions require reverse substitution to use OpenAI

### ISSUE THREAD

**Issue by vaecou** [sashabaranov/go-openai#405]
Can you customize the API address? Some regions require reverse substitution to use OpenAI

**Comment by vvatanabe** [comment]
@vaecou  You can customize the base URL.

```
cfg := openai.DefaultConfig("OPENAI_APIKEY")
cfg.BaseURL = "CUSTOM_URL" // default is https://api.openai.com/v1
```

**Comment by vaecou** [comment]
@vvatanabe Thank you for your reply. It has been resolved through your method!

**Comment by jmacwhyte** [comment]
@vaecou Please close this issue if it has been resolved, thanks! :)
