### ISSUE TITLE
Model hyperparams with Temperature value 0 is not being respected

### ISSUE THREAD

**Issue by nmanchinn** [sashabaranov/go-openai#413]
**Describe the bug**
When clients set the model hyperparameters like Temperature to 0, they are being ignored and not sent to OpenAI. This causes LLM to use their default values ( for example, temperature 1 )

**To Reproduce**
While creating the request set the temperature value to 0

This will send the request to OpenAI as below
```
"{\"model\":\"gpt-3.5-turbo-0301\",\"messages\":[{\"role\":\"system\",\"content\":\"You are an AI Chatbot. Follow the user's instructions carefully. Respond using markdown. You have a knowledge cutoff of 2021.\"},{\"role\":\"user\",\"content\":\"What are the 3 topics I asked you to write about?\"}],\"max_tokens\":2048,\"stream\":true}"
```

**Expected behavior**
Temperature 0 should be sent to openai
"{\"model\":\"gpt-3.5-turbo-0301\",\"messages\":[{\"role\":\"system\",\"content\":\"You are an AI Chatbot. Follow the user's instructions carefully. Respond using markdown. You have a knowledge cutoff of 2021.\"},{\"role\":\"user\",\"content\":\"What are the 3 topics I asked you to write about?\"}],\"max_tokens\":2048,\"temperature\":0,\"stream\":true}"
```

**Screenshots/Logs**
This is the the request sent to OpenAI
```
"{\"model\":\"gpt-3.5-turbo-0301\",\"messages\":[{\"role\":\"system\",\"content\":\"You are an AI Chatbot. Follow the user's instructions carefully. Respond using markdown. You have a knowledge cutoff of 2021.\"},{\"role\":\"user\",\"content\":\"What are the 3 topics I asked you to write about?\"}],\"max_tokens\":2048,\"stream\":true}"
```

**Environment (please complete the following information):**
 - go-openai version:  v1.11.1
 - Go version:1.20
 - OpenAI API version: v1
 - OS: Ubuntu 20.04

**Comment by nmanchinn** [comment]
This issue is with the omitempty field tag: https://github.com/sashabaranov/go-openai/blob/master/chat.go#L48

**Comment by vvatanabe** [comment]
@nmanchinn Thanks for feedback! This problem has already been reported. Please see #9.

**Comment by vvatanabe** [comment]
This is a duplicate issue with https://github.com/sashabaranov/go-openai/issues/9, so please discuss it in https://github.com/sashabaranov/go-openai/issues/9 from now on.
