### ISSUE TITLE
go-openai /chat_stream.go steam model request openai if get error，this function cannot get error msg

### ISSUE THREAD

**Issue by zdjniubi** [sashabaranov/go-openai#424]
resp, err := sendRequestStream[ChatCompletionStreamResponse](c, req)
	if err != nil {
		return  // just return in this case req is nil, error is nil, we cannot know what error occur and it's detail
	}

**Comment by vvatanabe** [comment]
@zdjniubi  This error is being assigned to the err variable as a Named return value.

```
func (c *Client) CreateChatCompletionStream(
	ctx context.Context,
	request ChatCompletionRequest,
) (stream *ChatCompletionStream, err error) { <= here
```

**Comment by zdjniubi** [comment]
> @zdjniubi This error is being assigned to the err variable as a Named return value.
> 
> ```
> func (c *Client) CreateChatCompletionStream(
> 	ctx context.Context,
> 	request ChatCompletionRequest,
> ) (stream *ChatCompletionStream, err error) { <= here
> ```

If this function could return both error and stream with nil ?

**Comment by vvatanabe** [comment]
@zdjniubi The `CreateChatCompletionStream` function returns two values, a stream and an err. By examining each location of the return statements, we can think of the following four scenarios:

1. When the endpoint does not support the model:
The function returns along with the error ErrChatCompletionInvalidModel. In this case, the return value of the stream is nil, but err is not nil.

2. If an error occurs while creating a new request:
The error will be returned. In this case as well, the return value stream is nil, but err is not.

3. If an error occurs during the transmission of the request:
That error will be returned. In this scenario, the return value stream is also nil, and err is not nil. This error is being assigned to the err variable as a Named return value.

4. If the transmission of the request is successful and no error occurs:
The stream is returned as the return value, and err is nil.

Therefore, there is no scenario where this function returns both err and stream as nil. Regardless of the path taken, either the stream or err is always set to a value that is not nil.

```
func (c *Client) CreateChatCompletionStream(
	ctx context.Context,
	request ChatCompletionRequest,
) (stream *ChatCompletionStream, err error) {
	urlSuffix := chatCompletionsSuffix
	if !checkEndpointSupportsModel(urlSuffix, request.Model) {
		err = ErrChatCompletionInvalidModel // <= 1. When the endpoint does not support the model
		return
	}

	request.Stream = true
	req, err := c.newRequest(ctx, http.MethodPost, c.fullURL(urlSuffix, request.Model), withBody(request))
	if err != nil {
		return nil, err // <= 2. If an error occurs while creating a new request
	}

	resp, err := sendRequestStream[ChatCompletionStreamResponse](c, req)
	if err != nil {
		return // <= 3. If an error occurs during the transmission of the request
	}
	stream = &ChatCompletionStream{
		streamReader: resp,
	}
	return // <= 4. If the transmission of the request is successful and no error occurs: 
}
```

**Comment by vvatanabe** [comment]
This issue will be closed due to inactivity.
