### ISSUE TITLE
 Invalid schema for function 'get_current_weather': None is not of type 'object'

### ISSUE THREAD

**Issue by mehulgohil** [sashabaranov/go-openai#432]
**Describe the bug**
When calling  CreateChatCompletion with function call getting error 400.
ChatCompletion error: error, status code: 400, message: Invalid schema for function 'get_current_weather': None is not of type 'object'

**Expected behavior**
Expected behaviorwas to return the function call definition

**Screenshots/Logs**
<img width="354" alt="image" src="https://github.com/sashabaranov/go-openai/assets/28588619/7f8639e3-b394-4d46-8160-8d7def74b92a">

**Environment (please complete the following information):**
 - go-openai version: [e.g. v1.12.0]
 - Go version: [e.g. 1.18]
 - OpenAI API version: [e.g. v1]
 - OS: [e.g. Ubuntu 20.04]

**Comment by vvatanabe** [comment]
Duplicate #429

**Comment by vvatanabe** [comment]
Fixed https://github.com/sashabaranov/go-openai/pull/434
