### ISSUE TITLE
How can i compute the token count？

### ISSUE THREAD

**Issue by krisice** [sashabaranov/go-openai#442]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sashabaranov/go-openai/issues) before creating one.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vvatanabe** [comment]
@whisperkris  It seems that compute the token count has already been discussed. Please check https://github.com/sashabaranov/go-openai/issues/62.

[FYI] Good example of how to count tokens:
- https://github.com/pkoukk/tiktoken-go#counting-tokens-for-chat-api-calls
- https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb

**Comment by vvatanabe** [comment]
Please continue the discussion here. https://github.com/sashabaranov/go-openai/issues/62.
