### ISSUE TITLE
How to continue the discussion based on the historical conversation

### ISSUE THREAD

**Issue by jhonroxton** [sashabaranov/go-openai#445]
I want to develop an application where users can start a new conversation after login. When the user logs out and logs in again, I want them to be able to continue the discussion based on their previous conversation history. How can I make GPT retrieve context information from historical dialogues?

**Comment by vvatanabe** [comment]
@jhonroxton The OpenAI API does not retain conversation history. It must be maintained in an external persistence mechanism. There seems to be an OSS project using MongoDB. Please check https://github.com/sashabaranov/go-openai/issues/85#issuecomment-1446188519.

**Comment by jhonroxton** [comment]
> @jhonroxton The OpenAI API does not retain conversation history. It must be maintained in an external persistence mechanism. There seems to be an OSS project using MongoDB. Please check [#85 (comment)](https://github.com/sashabaranov/go-openai/issues/85#issuecomment-1446188519).

thanks for your reply, i'll try!

**Comment by jhonroxton** [comment]
> @jhonroxton The OpenAI API does not retain conversation history. It must be maintained in an external persistence mechanism. There seems to be an OSS project using MongoDB. Please check [#85 (comment)](https://github.com/sashabaranov/go-openai/issues/85#issuecomment-1446188519).

thanks for your reply, i'll try it!
