### ISSUE TITLE
How to call the chatgpt4.0 API

### ISSUE THREAD

**Issue by zxyAcmen** [sashabaranov/go-openai#459]
please add gpt4.0 api use example

**Comment by ZeroDeng01** [comment]
The calling method of GPT4.0 and GPT3.5 is the same, but the name of the incoming model is different

See commit: [d529d13](https://github.com/sashabaranov/go-openai/commit/d529d13ba15d31928a414f83f9ae9730d0a9223b)

**Comment by zxyAcmen** [comment]
Stream error: error, The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

I am already a subscribed user. But it still prompts this error. Is there any way to solve it?

**Comment by zxyAcmen** [comment]
On July 6, 2023 , we gave access to the [GPT-4 API](https://platform.openai.com/docs/models/gpt-4) (8k) to all API users who have made a successful payment of $1 or more.
and how can i use gpt-4(8k) api

**Comment by ZeroDeng01** [comment]
@zxyAcmen Maybe, you can use `CURL` or `Postman` to test. If you want, please show the `CURL` log here,
*Please pay attention and protect your privacy, such as KEY and other information should not be displayed here.*

**Comment by zxyAcmen** [comment]
"The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.",

**Comment by springhyp** [comment]
func TestGpt4(t *testing.T) {
	config := openai.DefaultConfig("replace your api key")
	config.OrgID = "replace your orgId"
	c := openai.NewClientWithConfig(config)
	ctx := context.Background()

	message := make([]openai.ChatCompletionMessage, 0)

	message = append(message, openai.ChatCompletionMessage{
		Role:    "user",
		Content: "你是谁？",
	})
	req := openai.ChatCompletionRequest{
		Model:    openai.GPT4,
		Messages: message,
	}
	resp, err := c.CreateChatCompletion(ctx, req)
	if err != nil {
		return
	}
	fmt.Println(resp.Choices[0].Message.Content)
}
