### ISSUE TITLE
Established connection failed because connected host has failed to respond.

### ISSUE THREAD

**Issue by KingJacM** [sashabaranov/go-openai#467]
**Describe the bug**
ChatCompletion error of "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond." when I built the go backend using gin and request the local endpoint from the frontend. I am currently in China, using VPN, and am able to access GPT on my browser well. Also, the key should be correct, and the account status is fine, I have tried two accounts, one with gpt4 and credit card, one without, doesn't make a difference.

**To Reproduce**
The code is below, really, just used the example in README, the code itself should be correct.
```go
// from another place
package types

type RecommendationRequest struct {
	Prompt string `json:"prompt"`
}

// main()
func main() {
	r := gin.Default()
	config := cors.DefaultConfig()
	config.AllowAllOrigins = true                            // Allow all origins
	config.AllowMethods = []string{"GET", "POST"}            // Specify what methods should be allowed
	config.AllowHeaders = []string{"Origin", "Content-Type"} // Specify what headers should be allowed
	r.Use(cors.New(config))
	api := r.Group("/api")
	{
		api.GET("/recommendations", handlers.GetRecommendations)
	}
	r.Run() // listen and serve on 0.0.0.0:8080
}


// heres the handler
func GetRecommendations(c *gin.Context) {
	var request types.RecommendationRequest

	// Append your request with specific instructions
	request.Prompt += " Please provide 9 recommendations in the following format: 'title: movie title, description: movie description and reason it matches my request, link: movie link'."

	client := openai.NewClient("sk-xxxxx")

	resp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model: openai.GPT3Dot5Turbo,
			Messages: []openai.ChatCompletionMessage{
				{
					Role:    openai.ChatMessageRoleUser,
					Content: request.Prompt,
				},
			},
		},
	)

	if err != nil {
		fmt.Printf("ChatCompletion error: %v\n", err)
		c.JSON(http.StatusInternalServerError, gin.H{"error": "Error getting recommendation."})
		return
	}

	... // not important, error always caught above
}

```

**Expected behavior**
A 200 response, so no error. 

**Screenshots/Logs**
```
[GIN-debug] Listening and serving HTTP on :8080
ChatCompletion error: Post "https://api.openai.com/v1/chat/completions": dial tcp 199.59.150.12:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
[GIN] 2023/08/04 - 03:53:06 | 500 |    21.052114s |             ::1 | GET      "/api/recommendations"
```

**Environment (please complete the following information):**
 - go-openai version: just ran go get at the day of starting this issue.
 - Go version: go version go1.20.6 windows/amd64
 - OpenAI API version: [e.g. v1]](https://api.openai.com/v1/chat/completions)
 - OS: Windows 11

**Additional context**
I suspect it might be caused of VPN, but I could access the GPT from my browser with no problem, and no problem going on any website, hence I'm confused. I hope someone who experienced similar case or anyone could give any advice could help me.

**Comment by ZeroDeng01** [comment]
If you use ss or v2ray, there will be some problems, unless you force a VPN tunnel for your IDE and operating environment. It is recommended to set the http client proxy as follows:
```go
transport := &http.Transport{
	Proxy: http.ProxyURL(“PROXY_URL”),
}
config.HTTPClient = &http.Client{
	Transport: transport,
	Timeout:   time.Second * 60,
}
config.BaseURL = "OPENAI_API_URL"
client = openai.NewClientWithConfig(config)
```

**Comment by KingJacM** [comment]
I used this 👇 proxy and it worked, didn't use the library tho, look into my repo "movie-ai" if you need more detail.
https://api.openai-proxy.com/v1/chat/completions
