### ISSUE TITLE
trying to provide a list of functions and receive an error

### ISSUE THREAD

**Issue by evdanil** [sashabaranov/go-openai#469]
**Describe the bug**
Attempt of sending request to completion endpoint return an error
" status code: 400, message: Invalid schema for function 'get_current_weather': None is not of type 'object' "

**To Reproduce**
Steps to reproduce the behavior, including any relevant code snippets.

	functions := []openai.FunctionDefinition{
		{
			Name: "get_current_weather",
			Parameters: jsonschema.Definition{
				Type: jsonschema.Object,
				Properties: map[string]jsonschema.Definition{
					"location": {
						Type:        jsonschema.String,
						Description: "The city and state, e.g. San Francisco, CA",
					},
					"unit": {
						Type: jsonschema.String,
						Enum: []string{"celcius", "fahrenheit"},
					},
				},
				Required: []string{"location"},
			},
		},
	}

	client := openai.NewClient(GPT_TOKEN)

	response, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model:     openai.GPT3Dot5Turbo0613,
			Messages:  chat_context.Messages,
			Functions: functions,
		},
	)

**Expected behavior**
API to consume functions list

**Environment (please complete the following information):**
- go-openai v1.14.1
- go version go1.20.7 linux/amd64
 - OpenAI API version: v1
 - OS: Ubuntu 20.04

**Comment by vvatanabe** [comment]
@evdanil This problem fixed https://github.com/sashabaranov/go-openai/pull/434.
Just to be sure, I tested with v1.14.1 using your code and it worked fine.

**Comment by evdanil** [comment]
Hello,

yes it is fixed indeed, for some reason, json.go I had in my code, was not up to date. Thank you for quick response.
