### ISSUE TITLE
How to get token usage in ChatCompletionStreamResponse？

### ISSUE THREAD

**Issue by wlevene** [sashabaranov/go-openai#470]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sashabaranov/go-openai/issues) before creating one.

**Describe the bug**
A clear and concise description of what the bug is. If it's an API-related bug, please provide relevant endpoint(s).

**To Reproduce**
Steps to reproduce the behavior, including any relevant code snippets.

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem. For non-graphical issues, please provide any relevant logs or stack traces.

**Environment (please complete the following information):**
 - go-openai version: [e.g. v1.12.0]
 - Go version: [e.g. 1.18]
 - OpenAI API version: [e.g. v1]
 - OS: [e.g. Ubuntu 20.04]

**Additional context**

**Comment by vvatanabe** [comment]
@wlevene Please check it:
https://github.com/sashabaranov/go-openai#does-go-openai-provide-a-method-to-count-tokens
