### ISSUE TITLE
4096 token budget thow error

### ISSUE THREAD

**Issue by seatext** [sashabaranov/go-openai#472]
**Describe the bug**
Gpt35 turbo endpoint dont accept 4000 tokens

*
 - go-openai version: [e.g. v1.12.0]
 - Go version: [e.g. 1.18]
 - OpenAI API version: [e.g. v1]
 - OS: [e.g. Ubuntu 20.04]

**Comment by vvatanabe** [comment]
@seatext Please use the bug template correctly and provide detailed information.

**Comment by vvatanabe** [comment]
@seatext  If you are not comfortable entering detailed information and would like to ask a question more casually, please ask it in the [discussion](https://github.com/sashabaranov/go-openai/discussions).
