### ISSUE TITLE
10x slowdown just for allowing GPT functions

### ISSUE THREAD

**Issue by ijt** [sashabaranov/go-openai#474]
**Describe the bug**

Handling function calls means waiting about 10s rather than under 1s for the response stream to start.

**To Reproduce**

Put this code into main.go. Then run

$ go run main.go
$ go run main.go -skipfuncs  # over 10x faster when I ran it

```go
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"github.com/sashabaranov/go-openai"
	"io"
	"log"
	"os"
	"time"
)

func main() {
	if err := slownessDemo(); err != nil {
		log.Fatalf("slowness-demo: %v", err)
	}
}

func slownessDemo() error {
	skippingFuncs := flag.Bool("skipfuncs", false, "whether to disable GPT function calls")
	flag.Parse()

	t0 := time.Now()

	key := os.Getenv("OPENAI_API_KEY")
	client := openai.NewClient(key)

	var msgs = []openai.ChatCompletionMessage{
		{
			Role:         "user",
			Content:      "What are the first 100 primes?",
			Name:         "",
			FunctionCall: nil,
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	if !*skippingFuncs {
		for {
			req := openai.ChatCompletionRequest{
				Model:     openai.GPT3Dot5Turbo,
				MaxTokens: 0,
				Messages:  msgs,
				Stream:    false,
				// The slowness occurs even with an empty Functions field.
				Functions: []openai.FunctionDefinition{},
			}
			resp, err := client.CreateChatCompletion(ctx, req)
			if err != nil {
				return fmt.Errorf("creating chat completion with fn call result: %w", err)
			}

			choice := resp.Choices[0]
			if choice.FinishReason == "stop" || choice.FinishReason == "length" {
				break
			}
			if choice.FinishReason == "function_call" {
				fc := resp.Choices[0].Message.FunctionCall
				f := funcs[fc.Name]
				y, err := f(fc.Arguments)
				if err != nil {
					emsg := fmt.Sprintf("calling func %s: %v", fc.Name, err)
					y = emsg
				}

				msgs = append(msgs, openai.ChatCompletionMessage{
					Role:         openai.ChatMessageRoleAssistant,
					Content:      "",
					FunctionCall: fc,
				})

				msgs = append(msgs, openai.ChatCompletionMessage{
					Role:    openai.ChatMessageRoleFunction,
					Name:    fc.Name,
					Content: y,
				})
			}
		}
	}

	req := openai.ChatCompletionRequest{
		Model:     openai.GPT3Dot5Turbo,
		MaxTokens: 1024,
		Messages:  msgs,
		Stream:    true,
	}
	stream, err := client.CreateChatCompletionStream(ctx, req)
	if err != nil {
		return fmt.Errorf("creating chat completion with fn call result: %w", err)
	}
	defer stream.Close()

	dt := time.Now().Sub(t0)
	log.Printf("time to stream start: %v", dt)

	for {
		response, err := stream.Recv()
		if errors.Is(err, io.EOF) {
			break
		}

		if err != nil {
			return fmt.Errorf("stream error: %w", err)
		}

		for _, choice := range response.Choices {
			chunk := choice.Delta.Content
			fmt.Print(chunk)
		}
	}

	return nil
}

var funcs = map[string]func(string) (string, error){}
```

**Expected behavior**
I expected support for functions not to hurt the performance so much.

**Screenshots/Logs**

$ go run main.go                                                                                    
2023/08/15 22:51:37 time to stream start: 10.546153166s
The first 100 prime numbers are as follows:

2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541⏎                                                                                                                                        

$ go run main.go -skipfuncs                                                                       
2023/08/15 22:51:51 time to stream start: 628.3405ms
The first 100 prime numbers are as follows:

2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599.⏎ 

**Environment (please complete the following information):**
 - go-openai version: v1.14.1
 - Go version: go version go1.20.4 darwin/arm64
 - OpenAI API version: v1
 - OS: Mac OS: Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000

**Additional context**

**Comment by vvatanabe** [comment]
@ijt The reason it's taking time is due to the following response. Simply put, the Stream is set to false, so I will calculate and respond with the first 100 prime numbers.

```go
req := openai.ChatCompletionRequest{
	Model:     openai.GPT3Dot5Turbo,
	MaxTokens: 0,
	Messages:  msgs,
	Stream:    false,
	// The slowness occurs even with an empty Functions field.
	Functions: []openai.FunctionDefinition{},
}
resp, err := client.CreateChatCompletion(ctx, req)
if err != nil {
	return fmt.Errorf("creating chat completion with fn call result: %w", err)
}
```

**Comment by ijt** [comment]
I thought that was necessary to allow function calls.

Is there some example code that can call functions when necessary and stream a response to the user when that is called for, without a massive slowdown?
