### ISSUE TITLE
Whether go-openai supports high concurrency

### ISSUE THREAD

**Issue by KpiHang** [sashabaranov/go-openai#478]
Hello, I want to know whether go-openai supports high concurrency?

I want to send requests to openai with high concurrency. If it is possible, how should I achieve it? Thank you very much.

**Comment by sashabaranov** [comment]
@KpiHang internally, go-openai uses the standard Go HTTP client, so all concurrency properties translate from there. Could you maybe give a more concrete example?

**Comment by KpiHang** [comment]
@sashabaranov  thx for your replay. To do some test for GPT，I want to use multiple accounts to send many different requests in parallel.

**Comment by sashabaranov** [comment]
@KpiHang sure thing, you'll just need to create multiple clients
