### ISSUE TITLE
429 error 

### ISSUE THREAD

**Issue by N0nEx1stEnt** [sashabaranov/go-openai#482]
error, status code: 429, message: You exceeded your current quota, please check your plan and billing details.

-> Hello, can u help me with this problem, please?)

**Comment by Heliner** [comment]
There seems to be some bug related to openai? API call frequency exceeds limit

**Comment by DominikLutley** [comment]
Hello, I'm getting the same error with just a basic Chat Completion. Has anyone figured out what the cause is? API key works just fine in OpenAI playground.

**Comment by N0nEx1stEnt** [comment]
Yes, I looked at the account from which the API was used, it was created more than 3 months ago, in order to continue the interaction, it was necessary to link a card (with which there will be a monthly payment for using the API), as a similar solution, we can simply create a new account and use the API without mistakes

I have a project related to telegrams (we just decided to make ChatGPT for employees with online access, after linking the cards they rolled out the release and actively use it)

I hope I helped you))

**Comment by DominikLutley** [comment]
For anyone wondering, I managed to solve this. In my case the error was that I belong to multiple organizations on the OpenAI platform, and the default one was the one that was expired. You can specify the organization if you use openai.NewClientWithConfig
