### ISSUE TITLE
Is it possible to add a custom header in the RequestBuild or have a funcation like AddHeaders()?

### ISSUE THREAD

**Issue by dumbsheep1990** [sashabaranov/go-openai#483]

**Comment by koterin** [comment]
Agreed, we could add `AdditionalHeaders` to `ClientConfig` and then add them in `setCommonHeaders()` like this

```
...
if len(c.config.AdditionalHeaders) > 0 {
		for k, v := range c.config.AdditionalHeaders {
			for _, val := range v {
				req.Header.Add(k, val)
			}
		}
	}
...
```

This would make this lib a perfect connector via VPNs that require additional headers or even [OpenRouter](https://openrouter.ai/docs) that can connect to multiple other AIs like meta-llama and google.

**Comment by chil-pavn** [comment]
any idea if the above is implemented or an alternative approach. I want to use this package to use with openrouter
