### ISSUE TITLE
DALL•E 3 support

### ISSUE THREAD

**Issue by sashabaranov** [sashabaranov/go-openai#494]
Following up on a new release: https://openai.com/dall-e-3

**Comment by yangkequn** [comment]
DALL•E 3 support  is badly needed. 
it's widely accessible using chatgpt plus account, using model=gpt-4-dalle
Life is awfull when such a candy missing

**Comment by Peakz** [comment]
> DALL•E 3 support is badly needed. it's widely accessible using chatgpt plus account, using model=gpt-4-dalle Life is awfull when such a candy missing

DALL·E 3 model isn't accessible through the official API, only DALL·E 2. See https://platform.openai.com/docs/models/dall-e

**Comment by govida** [comment]
I saw dalle-3 has ready published, [image guides](https://platform.openai.com/docs/guides/images/usage), will there follow?

**Comment by vvatanabe** [comment]
Done https://github.com/sashabaranov/go-openai/releases/tag/v1.17.3
