### ISSUE TITLE
Support response_format parameter

### ISSUE THREAD

**Issue by mattbrandman** [sashabaranov/go-openai#521]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/sashabaranov/go-openai/issues) before creating one.

**Is your feature request related to a problem? Please describe.**
OpenAI recently unveiled a new optional parameter response_format that allows for json only responses. Could this be added into the library?

**Describe the solution you'd like**
Response_format supported.

**Describe alternatives you've considered**
N/A

**Comment by simonklee** [comment]
Link to docs for `response_format`: https://platform.openai.com/docs/api-reference/chat/create#chat-create-response_format

**Comment by aghchan** [comment]
is it possible to get this in? a bit confused by the link provided to the docs (as if it could work with the current client implementation)

**Comment by simonklee** [comment]
No — my intention was simply to add a link to the docs describing the feature you're asking about.

**Comment by simonklee** [comment]
Merging https://github.com/sashabaranov/go-openai/pull/525 should resolve this issue.
