### ISSUE TITLE
CreateChatCompletion() fails with error, status code: 400, message: '' is not one of ['json_object', 'text'] - 'response_format.type'

### ISSUE THREAD

**Issue by mikeb26** [sashabaranov/go-openai#541]
**Describe the bug**
v1.17.0 introduced a regression into CreateChatCompletion() when using the 3.5 Turbo model. Now this function is failing with:
error, status code: 400, message: '' is not one of ['json_object', 'text'] - 'response_format.type'

If I switch back to v1.16.1 the problem goes away.

**To Reproduce**
```
	client := openai.NewClient(MYKEY)
	dialogue := []openai.ChatCompletionMessage{
		{Role: openai.ChatMessageRoleSystem, Content: MYSYSTEMMSG},
		{Role: openai.ChatMessageRoleUser, Content: MYPROMPT},
	}

	resp, err := client.CreateChatCompletion(
		context.Background(),
		openai.ChatCompletionRequest{
			Model:    openai.GPT3Dot5Turbo,
			Messages: dialogue,
		},
	)
	if err != nil {
		return err  <-- v1.17.0 fails here
	}
```

**Expected behavior**
Non-error return.

**Screenshots/Logs**

**Environment (please complete the following information):**
 - go-openai version: v1.17.0
 - Go version: 1.21.3
 - OpenAI API version: v1
 - OS: Ubuntu 20.04.6 LTS

**Additional context**
n/a

**Comment by mikeb26** [comment]
It looks like commit 6d9c3a6365643d02692ecc6f0b34a5fa3e7fea45 introduced this regression. If I revert it locally the problem goes away. @henomis can you take a look?

**Comment by jackieli-tes** [comment]
oops, filed the same one as you. I searched before drafting :D #542

**Comment by henomis** [comment]
PR here: https://github.com/sashabaranov/go-openai/pull/544

**Comment by vvatanabe** [comment]
@sashabaranov @mikeb26 @jackieli-tes @henomis 
Released the fix for this issue:
https://github.com/sashabaranov/go-openai/releases/tag/v1.17.2
