### ISSUE TITLE
ChatGPT example usage in Readme.reports an error 

### ISSUE THREAD

**Issue by hcws** [sashabaranov/go-openai#553]
I just use my apikey and build 、run the demo,it reports an error,bellow
 
status code: 400, message: '' is not one of ['json_object', 'text'] - 'response_format.type'

**Comment by vvatanabe** [comment]
@hcws That problem has been fixed in [v1.17.3](https://github.com/sashabaranov/go-openai/releases/tag/v1.17.3). Update and try it out. Refs: #544

**Comment by hcws** [comment]
Well done！Thanks.
