### ISSUE TITLE
dial api

### ISSUE THREAD

**Issue by gitlayzer** [sashabaranov/go-openai#604]
With the same key and the same IP, OpenAI's Python package can be used, but it is not possible to use go-openai. It reports an error and cannot parse the api.

![image](https://github.com/sashabaranov/go-openai/assets/77761224/5ab5a7ee-9ee2-472c-b896-ee68f0edb50b)

**Comment by kmesiab** [comment]
Looks like it's not making it far enough. The error is reporting you have a connectivity problem.

**Comment by github-zjh** [comment]
me too

**Comment by github-zjh** [comment]
> With the same key and the same IP, OpenAI's Python package can be used, but it is not possible to use go-openai. It reports an error and cannot parse the api.
> 
> ![image](https://private-user-images.githubusercontent.com/77761224/285119017-5ab5a7ee-9ee2-472c-b896-ee68f0edb50b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjgyNzksIm5iZiI6MTcwMTMyNzk3OSwicGF0aCI6Ii83Nzc2MTIyNC8yODUxMTkwMTctNWFiNWE3ZWUtOWVlMi00NzJjLWI4OTYtZWU2OGYwZWRiNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTYwYjcwOTNjNTY1MzBmNjhiOGVmZjRmNWNmY2YzMzM4MjU2MDBhNGQ5OGExNDNjNjhmYWIzZmY3NDdkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_uC9ePNF0i_52wg5EspgBW__GYzWKs-m8WPvtcyuSE)

哥们 解决了吗 我本地测试也是  用curl就行  用他这个go的sdk就同样的dial tcp超时

**Comment by gitlayzer** [comment]
> > 相同密钥、相同IP，可以使用OpenAI的Python包，但不能使用go-openai。报错，无法解析api。
> > ![图像](https://private-user-images.githubusercontent.com/77761224/285119017-5ab5a7ee-9ee2-472c-b896-ee68f0edb50b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjgyNzksIm5iZiI6MTcwMTMyNzk3OSwicGF0aCI6Ii83Nzc2MTIyNC8yODUxMTkwMTctNWFiNWE3ZWUtOWVlMi00NzJjLWI4OTYtZWU2OGYwZWRiNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTYwYjcwOTNjNTY1MzBmNjhiOGVmZjRmNWNmY2YzMzM4MjU2MDBhNGQ5OGExNDNjNjhmYWIzZmY3NDdkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_uC9ePNF0i_52wg5EspgBW__GYzWKs-m8WPvtcyuSE)
> 
> 哥们 解决了吗 我本地测试也是 用curl就行 用他这个go的sdk就同样的dial tcp超时

欸，我用 Python 了

**Comment by gitlayzer** [comment]
> Looks like it's not making it far enough. The error is reporting you have a connectivity problem.

No no no There is no problem with my connection

**Comment by maybeluo** [comment]
I get the same problem when using GPT3Dot5Turbo1106.

**Comment by github-zjh** [comment]
哈哈  我解决了 其实设置个代理就OK啦

`const (
	ApiKey    = "sk-xxxxxxxxxxxxxxxxxxx"
	ProxyHost = "http://127.0.0.1:10809"
)

var client *openai.Client

func init() {
	proxyUri, err := url.Parse(ProxyHost)
	if err != nil {
		return
	}
	hClient := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(proxyUri),
		},
		Timeout: 60 * time.Second,
	}
	defaultConfig := openai.DefaultConfig(ApiKey)
	defaultConfig.HTTPClient = hClient
	client = openai.NewClientWithConfig(defaultConfig)
}`

> > > 相同密钥、相同IP，可以使用OpenAI的Python包，但不能使用go-openai。报错，无法解析api。
> > > ![图像](https://private-user-images.githubusercontent.com/77761224/285119017-5ab5a7ee-9ee2-472c-b896-ee68f0edb50b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjgyNzksIm5iZiI6MTcwMTMyNzk3OSwicGF0aCI6Ii83Nzc2MTIyNC8yODUxMTkwMTctNWFiNWE3ZWUtOWVlMi00NzJjLWI4OTYtZWU2OGYwZWRiNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTYwYjcwOTNjNTY1MzBmNjhiOGVmZjRmNWNmY2YzMzM4MjU2MDBhNGQ5OGExNDNjNjhmYWIzZmY3NDdkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_uC9ePNF0i_52wg5EspgBW__GYzWKs-m8WPvtcyuSE)
> > 
> > 
> > 哥们 解决了吗 我本地测试也是 用curl就行 用他这个go的sdk就同样的dial tcp超时
> 
> 欸，我用 Python 了

**Comment by github-zjh** [comment]
> I get the same problem when using GPT3Dot5Turbo1106:
> 
> > Completion error: err:Post "https://api.openai.com/v1/chat/completions": dial tcp xx.xx.xx.xx:443: connect: connection refused

Perhaps you should set up a proxy on the client side.

**Comment by ouyang6559** [comment]
> 哈哈 我解决了 其实设置个代理就OK啦
> 
> ```go
> const (
> 	ApiKey    = "sk-xxxxxxxxxxxxxxxxxxx"
> 	ProxyHost = "http://127.0.0.1:10809"
> )
> 
> var client *openai.Client
> 
> func init() {
> 	proxyUri, err := url.Parse(ProxyHost)
> 	if err != nil {
> 		return
> 	}
> 	hClient := &http.Client{
> 		Transport: &http.Transport{
> 			Proxy: http.ProxyURL(proxyUri),
> 		},
> 		Timeout: 60 * time.Second,
> 	}
> 	defaultConfig := openai.DefaultConfig(ApiKey)
> 	defaultConfig.HTTPClient = hClient
> 	client = openai.NewClientWithConfig(defaultConfig)
> }
> ```
> 
> > > > 相同密钥、相同IP，可以使用OpenAI的Python包，但不能使用go-openai。报错，无法解析api。
> > > > ![图像](https://private-user-images.githubusercontent.com/77761224/285119017-5ab5a7ee-9ee2-472c-b896-ee68f0edb50b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMjgyNzksIm5iZiI6MTcwMTMyNzk3OSwicGF0aCI6Ii83Nzc2MTIyNC8yODUxMTkwMTctNWFiNWE3ZWUtOWVlMi00NzJjLWI4OTYtZWU2OGYwZWRiNTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA3MDYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYTYwYjcwOTNjNTY1MzBmNjhiOGVmZjRmNWNmY2YzMzM4MjU2MDBhNGQ5OGExNDNjNjhmYWIzZmY3NDdkYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_uC9ePNF0i_52wg5EspgBW__GYzWKs-m8WPvtcyuSE)
> > > 
> > > 
> > > 哥们 解决了吗 我本地测试也是 用curl就行 用他这个go的sdk就同样的dial tcp超时
> > 
> > 
> > 欸，我用 Python 了

亲测有效，完整代码
```go

package main

import (
	"context"
	"fmt"
	gogpt "github.com/sashabaranov/go-openai"
	"net/http"
	"net/url"
	"time"
)

const (
	ApiKey    = "sk-"  //换自己的key
	ProxyHost = "http://127.0.0.1:7890"。//换自己vpn的端口，比如clashx就是7890端口
)

var client *gogpt.Client

func init() {
	proxyUri, err := url.Parse(ProxyHost)
	if err != nil {
		return
	}
	hClient := &http.Client{
		Transport: &http.Transport{
			Proxy: http.ProxyURL(proxyUri),
		},
		Timeout: 60 * time.Second,
	}
	defaultConfig := gogpt.DefaultConfig(ApiKey)
	defaultConfig.HTTPClient = hClient
	client = gogpt.NewClientWithConfig(defaultConfig)
}

func main() {
	resp, err := client.CreateChatCompletion(
		context.Background(),
		gogpt.ChatCompletionRequest{
			Model: gogpt.GPT3Dot5Turbo,
			Messages: []gogpt.ChatCompletionMessage{
				{
					Role:    gogpt.ChatMessageRoleUser,
					Content: "帮我写一份go语言入门教程",
				},
			},
		},
	)

	if err != nil {
		fmt.Printf("ChatCompletion error: %v\n", err)
		return
	}

	fmt.Println(resp.Choices[0].Message.Content)
}


```

**Comment by gitlayzer** [comment]
Okey! Thanks！
