### ISSUE TITLE
ChatCompletionStream error

### ISSUE THREAD

**Issue by 10suleyman01** [sashabaranov/go-openai#613]
ChatCompletionStream error: error, status code: 403, message: invalid character '<' looking for beginning of value

**Environment (please complete the following information):**
 - go-openai version: [e.g. v1.12.0]
 - Go version: [e.g. 1.18]
 - OpenAI API version: [e.g. v1]
 - OS: [e.g. Ubuntu 20.04]

**Comment by fr11nik** [comment]
How did you fix that issue ? @10suleyman01
