### ISSUE TITLE
invalid character 'H' looking for beginning of value

### ISSUE THREAD

**Issue by CNTWDev** [sashabaranov/go-openai#635]
**Describe the bug**
call api CreateTranslation
get error code: invalid character 'H' looking for beginning of value

**To Reproduce**
Steps to reproduce the behavior, including any relevant code snippets.

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots to help explain your problem. For non-graphical issues, please provide any relevant logs or stack traces.

**Environment (please complete the following information):**
 - go-openai version: 1.17.11
 - Go version: [e.g. 1.19]
 - OpenAI API version: [e.g. v1]
 - OS: Linux iZgw839frdaicos127vowbZ 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by CNTWDev** [comment]
@sashabaranov please help,thx

**Comment by CNTWDev** [comment]
@sashabaranov please

**Comment by sashabaranov** [comment]
@CNTWDev  could you please provide a minimal code example to reproduce this?

**Comment by CNTWDev** [comment]
`
	var req openai.ChatCompletionRequest
	if q.GPTVersion == 3 {
		req = openai.ChatCompletionRequest{
			Model: openai.GPT3Dot5Turbo,
			//MaxTokens: 200,
			Messages:    messages.OpenAIMessage,
			Temperature: math.SmallestNonzeroFloat32,
		}
	} else if q.GPTVersion == 4 {
		req = openai.ChatCompletionRequest{
			Model: openai.GPT4,
			//MaxTokens: 200,
			Messages:    messages.OpenAIMessage,
			Temperature: math.SmallestNonzeroFloat32,
		}
	}
	resp, err := gptClient.CreateChatCompletion(c, req)
	if err != nil {
		logger.ZapLog.Error("[ChatAudioIn]", zap.String("uuid", q.UUID), zap.Int("aiEngineID", q.AiEngine), zap.String("q", q.Question), zap.String("error", err.Error()))
		return nil, err
	} else {
		content := resp.Choices[0].Message.Content

		//  tts合成
		var ttsFileName string
		var ttsFilePath string
		logger.ZapLog.Info("[ChatAudioIn]", zap.String("content", content))
		if q.NeedTTS {
			ttsFileName, ttsFilePath, err = tts(c, content)
		}
		logger.ZapLog.Info("[ChatAudioIn]", zap.String("ttsFilePath", ttsFilePath), zap.String("ttsFileName", ttsFileName))
		if err != nil {
			logger.ZapLog.Error("[ChatAudioIn]", zap.Error(err))
			return nil, err
		}
		var save *ent.Chat
		if len(q.UUID) > 0 {
			if q.RecordID > 0 {
				save, err = DBEngine.Chat.Create().SetUUID(q.UUID).SetMessage(q.Question).SetContent(content).SetAudioQuestionURL(filepath.Base(q.AudioInPath)).SetAudioRespURL(ttsFileName).SetRecordID(q.RecordID).Save(c)
				if err != nil {
					logger.ZapLog.Error("[ChatAudioIn]", zap.Error(err))
					return nil, err
				}
			} else {
				save, err = DBEngine.Chat.Create().SetUUID(q.UUID).SetMessage(q.Question).SetContent(content).SetAudioQuestionURL(filepath.Base(q.AudioInPath)).SetAudioRespURL(ttsFileName).Save(c)
				if err != nil {
					logger.ZapLog.Error("[ChatAudioIn]", zap.Error(err))
					return nil, err
				}
			}
		}

`

**Comment by CNTWDev** [comment]
@sashabaranov thx, my friend

**Comment by CNTWDev** [comment]
I used the wrong format. 
Sorry about it. 
Closed
