### ISSUE TITLE
Demo code not working 

### ISSUE THREAD

**Issue by JuanVargas** [sashabaranov/go-openai#64]
Please forgive me if I am asking an insanely stupid question. I got the go-gpt3 code, then copied verbatim the example usage, and when I try to run the example code I get no response.  

I did not download anything else besides go-gpt3, therefore, here is the (potentially insanely stupid question): Do I need to download something else. e.g., the openai API in Python or in .js?

I don't like Python or JS, I would rather use pure Go if possible, but if there is no other choice and I have to get the Python or the JS version, which one would be the better choice?

Thanks you

**Comment by JuanVargas** [comment]
I found that the question was as I expected insanely silly. Just got the Open AI in Python (  :-(  )  to at least get the example demo working. I also need to get a token and so forth

**Comment by abraham2512** [comment]
You wouldnt need anything else except go-gpt3 and an auth token to make an API call to GPT-3 for completions.

**Comment by vvatanabe** [comment]
The problem seems to have resolved itself, so I'm closing it.
