### ISSUE TITLE
I can't set the openai.ClientConfig.authToken field

### ISSUE THREAD

**Issue by elcn233** [sashabaranov/go-openai#640]
I use go-openai v1.18.3

`				openaiConfig := openai.ClientConfig{
					authToken:  "<KEY>",
					APIType:    openai.APITypeOpenAI,
					BaseURL:    "https://api.openai.com/v1",
					HTTPClient: http.DefaultClient,
				}
				client := openai.NewClientWithConfig(openaiConfig)
				resp, err := client.CreateChatCompletion(
					context.Background(),
					openai.ChatCompletionRequest{
						Model: openai.GPT3Dot5Turbo,
						Messages: []openai.ChatCompletionMessage{
							{
								Role:    openai.ChatMessageRoleUser,
								Content: text,
							},
						},
					},
				)`
This is my code. My IDE reports an error in the authToken column because the authToken field is private. How can I set the authToken while setting the baseURL and HTTPClient fields?

**Comment by AspadaX** [comment]
it is quiet unintuitive, but for now, it works like this: 
```
	openaiConfig := openai.DefaultConfig(
		your api key here,
	)
	openaiConfig.BaseURL = your base url here
	
```

**Comment by elcn233** [comment]
> it is quiet counter-intuitive, but for now, it works like this:
> 
> ```
> 	openaiConfig := openai.DefaultConfig(
> 		your api key here,
> 	)
> 	openaiConfig.BaseURL = your base url here
> 	
> ```

okay, thanks a lot, it worked
