### ISSUE TITLE
Got Validation Error on Create Thread and Run

### ISSUE THREAD

**Issue by dibikhairurrazi** [sashabaranov/go-openai#663]
I have no problem running this code until today
<img width="574" alt="Screenshot 2024-02-17 at 18 06 18" src="https://github.com/sashabaranov/go-openai/assets/26002910/f3707a10-fa50-4953-8150-bf2bdc5eb372">
Now it return validation error. 
`error, status code: 400, message: 4 validation errors for Request\nbody -> tools -> 0 -> type\n  unexpected value; permitted: <ToolTypeParam.CODE_INTERPRETER: 'code_interpreter'> (type=value_error.const; given=retrieval; permitted=(<ToolTypeParam.CODE_INTERPRETER: 'code_interpreter'>,))\nbody -> tools -> 0 -> function\n  extra fields not permitted (type=value_error.extra)\nbody -> tools -> 0 -> function\n  extra fields not permitted (type=value_error.extra)\nbody -> tools -> 0 -> type\n  unexpected value; permitted: <ToolTypeParam.FUNCTION: 'function'> (type=value_error.const; given=retrieval; permitted=(<ToolTypeParam.FUNCTION: 'function'>,))`

Based on [this](https://community.openai.com/t/retrievals-tool-not-permitted/628664) thread, they made changes to the validation which disallow any unknown fields. Is there any way to solve this?

Thanks

Env:
 - go-openai version: 1.19.4
 - Go version: 1.21.4
 - OS: Mac OS 13.5

**Comment by CaoPengflying** [comment]
i have the same prolbem.
Official reply：
Hi all, we did recently tighten up the validation logic here, apologies for the issues. We now check for unknown fields in each tool definition and disallow them. This was a bug in our original validation logic that we intended to fix. [@CheongFan](https://community.openai.com/u/cheongfan) it looks like you might be passing “function: null” …

**Comment by dibikhairurrazi** [comment]
closing this, no issue after using the latest commit. thanks @CaoPengflying
