### ISSUE TITLE
ModifyMessage failed with error code 400, message: Unknown parameter

### ISSUE THREAD

**Issue by Ahmadhegavf** [sashabaranov/go-openai#692]
**Bug Description:**
The `ModifyMessage` function from the `go-openai` library expects a parameter `metadata` of type `map[string]any`, but the API it interfaces with, specifically the [Modify Message endpoint](https://platform.openai.com/docs/api-reference/messages/modifyMessage), requires the metadata to be wrapped in a JSON object with a field named `"metadata"`. This discrepancy causes the API call to fail due to an unknown parameter.

**To Reproduce:**
Call the `ModifyMessage` function with a non-empty `metadata` parameter.

**Expected Behavior:**
The method should serialize the metadata into a JSON object with a field named `"metadata"` and send it to the API, aligning with the API's expectations.

**Environment:**
- `go-openai` version: v1.120.3
- Go version: go1.21.3
- OpenAI API version: v1
- OS: Ubuntu 20.04

**Comment by qhenkart** [comment]
I just ran into this as well and you was going to make an issue. I can confirm this report
