### ISSUE TITLE
Azure openai assistans list interface parameter splicing error

### ISSUE THREAD

**Issue by WhiteNightMo** [sashabaranov/go-openai#794]
**Environment:**
 - go-openai version: v1.24.0
 - Go version: 1.19.10

**Screenshots/Logs**
![image](https://github.com/user-attachments/assets/39c6faee-8e9d-4e28-9531-adab20fda420)

**Additional context**
If the parameter contains paging information, the generated url will contain two question marks.
The output I printed: 
```
c.fullURL(urlSuffix): https://xxx.openai.azure.com/openai/assistants?limit=10?api-version=2023-05-15
```

**Comment by WhiteNightMo** [comment]
But the `baseURL` comes from the config file, and it's really the `suffix` that should be of concern.
```golang
baseURL := c.config.BaseURL
baseURL = strings.TrimRight(baseURL, "/")
parseURL, _ := url.Parse(baseURL)
```

Here's what I printed and it didn't change anything.
![image](https://github.com/user-attachments/assets/d0aa0baf-d579-486b-812e-609b39ca02f6)

**Comment by WhiteNightMo** [comment]
@eiixy @sashabaranov

**Comment by eiixy** [comment]
@WhiteNightMo Could you please check if the unit tests cover your use case? #817

**Comment by WhiteNightMo** [comment]
> @WhiteNightMo Could you please check if the unit tests cover your use case? #817

Thanks for the fix. For me, the [`/audio/speech`](https://platform.openai.com/docs/api-reference/audio/createSpeech) interface was missing from the judgment here. I'm not sure if there are other interfaces missing here.
```golang
if !containsSubstr([]string{
	"/completions",
	"/embeddings",
	"/chat/completions",
	"/audio/transcriptions",
	"/audio/translations",
	"/images/generations",
}, parseSuffix.Path) {
	return fmt.Sprintf("%s/%s%s?%s", baseURL, azureAPIPrefix, parseSuffix.Path, query.Encode())
}
```

**Comment by eiixy** [comment]
> > @WhiteNightMo Could you please check if the unit tests cover your use case? #817
> 
> Thanks for the fix. For me, the [`/audio/speech`](https://platform.openai.com/docs/api-reference/audio/createSpeech) interface was missing from the judgment here. I'm not sure if there are other interfaces missing here.
> 
> ```go
> if !containsSubstr([]string{
> 	"/completions",
> 	"/embeddings",
> 	"/chat/completions",
> 	"/audio/transcriptions",
> 	"/audio/translations",
> 	"/images/generations",
> }, parseSuffix.Path) {
> 	return fmt.Sprintf("%s/%s%s?%s", baseURL, azureAPIPrefix, parseSuffix.Path, query.Encode())
> }
> ```

I couldn't find any information about /audio/speech in the official Azure OpenAI documentation. Could you please provide a reference link to the documentation or further explain the origin and purpose of this endpoint?
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2024-06-01/inference.yaml

**Comment by WhiteNightMo** [comment]
OpenAI：https://platform.openai.com/docs/api-reference/audio/createSpeech
Azure OpenAI：https://learn.microsoft.com/en-us/azure/ai-services/openai/text-to-speech-quickstart?tabs=command-line#rest-api
