### ISSUE TITLE
Code examples

### ISSUE THREAD

**Issue by sashabaranov** [sashabaranov/go-openai#80]
I think we can do a better job with documentation by providing testable examples https://go.dev/blog/examples

**Comment by LordThevenin** [comment]
@sashabaranov I would love to contribute to this project, can I pick this issue?

**Comment by sashabaranov** [comment]
@LordThevenin yes, please! It would be cool to move out all tests with real API [token](https://github.com/sashabaranov/go-openai/blob/master/api_test.go#L15) into testable examples:.
