### ISSUE TITLE
Support for Structured Outputs

### ISSUE THREAD

**Issue by hari4698** [sashabaranov/go-openai#814]
I was wondering if there will support in the future for [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs). Open AI released this feature on August 6th.

### Python example from the Open API docs: 

```python
from pydantic import BaseModel
from openai import OpenAI

client = OpenAI()

class CalendarEvent(BaseModel):
    name: str
    date: str
    participants: list[str]

completion = client.beta.chat.completions.parse(
    model="gpt-4o-2024-08-06",
    messages=[
        {"role": "system", "content": "Extract the event information."},
        {"role": "user", "content": "Alice and Bob are going to a science fair on Friday."},
    ],
    response_format=CalendarEvent,
)

event = completion.choices[0].message.parsed
```

**Comment by h0rv** [comment]
I am looking to add support for the `strict` json schema too.

[instructor-go](https://github.com/instructor-ai/instructor-go) currently gives a similar experience as the python API provides, and in place for Pydantic it use Go struct tags and jsonschema.

**Comment by modeledge** [comment]
Great news. 

I'm not sure how you will approach implementing the actual json schema definition within the request but consider allowing for different implementations of the actual json schema creation. I started with field tags, as in [instructor-go](https://github.com/instructor-ai/instructor-go), but have since moved away from that approach and think field tags are too limiting.

**Comment by h0rv** [comment]
For instructor, JSON tags has been sufficient.

I have been struggling to convert the json schema to the currently defined struct here.

I think it would be great to optionally pass a raw schema to `response_format`.

For example, the current struct does not support defs, which are crucial, especially with complex data types. The OpenAI API supports this: https://platform.openai.com/docs/guides/structured-outputs/supported-schemas.

**Comment by monstercameron** [comment]
This enhancement would be great!

**Comment by rjcorwin** [comment]
Looks like this issue is resolved? https://github.com/sashabaranov/go-openai/pull/813

**Comment by h0rv** [comment]
My issue above is resolved: for those wanting to use their own schema string, and not use the `go-openai/jsonschema`, you can do the following:

```go
JSONSchema: &openai.ChatCompletionResponseFormatJSONSchema{
    Name:        "my-name",
    Schema:      json.RawMessage(schemaJSON),
    Strict:      true,
}
```

**Comment by hari4698** [comment]
Support added for Structured Output. #813
