### ISSUE TITLE
v1.28.0 breaks API requests that specify a response format without a JSONSchema

### ISSUE THREAD

**Issue by gspeicher** [sashabaranov/go-openai#818]
**Describe the bug**
The addition of the `JSONSchema` field to type `ChatCompletionResponseFormat` has broken API requests that specify `ResponseFormat` as `openai.ChatCompletionResponseFormatTypeJSONObject`. 

**To Reproduce**
```
        req := openai.ChatCompletionRequest{
                // ...
                ResponseFormat: &openai.ChatCompletionResponseFormat{
                        Type: openai.ChatCompletionResponseFormatTypeJSONObject,
                },
        }
        resp, err := o.Client.CreateChatCompletion(context.Background(), req)
```

**Expected behavior**
API requests should continue to work as before.

**Screenshots/Logs**
The API is responding with:
> Unknown parameter: 'response_format.json_schema'.

**Environment (please complete the following information):**
 - go-openai version: 1.28.0
 - Go version: 1.22.5
 - OpenAI API version: v1
 - OS: MacOS 14.6 (23G80)

**Additional context**
The problem is that `omitempty` does not respect the empty value for `JSONSchema` field since it is defined as a non-pointer type. If it is defined instead as a pointer to `ChatCompletionResponseFormatJSONSchema` then it will be correcly omitted from the marshaled JSON when not in use.

```
type ChatCompletionResponseFormat struct {
	Type       ChatCompletionResponseFormatType       `json:"type,omitempty"`
	JSONSchema ChatCompletionResponseFormatJSONSchema `json:"json_schema,omitempty"`
}
```

**Comment by gspeicher** [comment]
Tagging @eiixy as the original author of the breaking PR.

**Comment by tylergannon** [comment]
@gspeicher see #820.  Meanwhile if you want to get started using the new api before this gets merged, you can use my fork.  Just update your go.mod to use the following `replace` directive:

```
replace github.com/sashabaranov/go-openai => github.com/tylergannon/go-openai v1.28.1
```

**Comment by gspeicher** [comment]
Thanks, @tylergannon! While you're in there, maybe you can check out my note in #813 about changing the definition of the `ChatCompletionResponseFormatJSONSchema` type.

```
type ChatCompletionResponseFormatJSONSchema struct {
	Name        string                `json:"name"`
	Description string                `json:"description,omitempty"`
	Schema      jsonschema.Definition `json:"schema"`
	Strict      bool                  `json:"strict"`
}
```

My hope is that we can change the type of `Schema` to the `json.Marshaler` interface (from `encoding/json`) instead of forcing consumers to use `jsonschema.Definition` to declare the JSON schema. Even the godoc comments for that type state:

> It is fairly limited, and you may have better luck using a third-party library.

but explicitly defining `Schema` as above means you have no choice except to use `jsonschema.Definition`. Also worth mentioning that `jsonschema.Definition` already satisfies the `json.Marshaler` interface so all of the examples and tests should continue to work unchanged.

**Comment by fonsecabc** [comment]
I am also having this problem, is there any fix to it yet or the only option is to not use the response format?

**Comment by EduardoMoraesRitter** [comment]
I had a problem with this today.

**Comment by sashabaranov** [comment]
Fixed in https://github.com/sashabaranov/go-openai/releases/tag/v1.28.1
