### ISSUE TITLE
how make chatgpt API can remober last question?

### ISSUE THREAD

**Issue by hcws** [sashabaranov/go-openai#85]
I want to use `GPT3TextDavinci003` but it  can not remober last question ， And it supported ?

**Comment by alambertt** [comment]
Did  you use the streams?

**Comment by hcws** [comment]
yes
&nbsp;


蓝宝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Angel Lambertt ***@***.***&gt;; 
发送时间: 2023年2月24日(星期五) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [sashabaranov/go-gpt3] how make chatgpt API can remober last question? (Issue #85)





 
Did  you use the streams?

**Comment by nuixdt** [comment]
ChatGPT has context to remember the conversation. API TextDavinci003 is different from ChatGPT at that.

**Comment by ujjwall-R** [comment]
https://github.com/ujjwall-R/GPT3-wrapper-using-memorisation-in-GO.git

have a look into it guys. I build the memorisation feature using mongodb. Basically, the bot remembers the user with particular userid
