### ISSUE TITLE
Base url

### ISSUE THREAD

**Issue by ashish111333** [sashabaranov/go-openai#886]
is it possible to change base Url for chat completion requests ?

**Comment by wcu1117** [comment]
i had the same error,when I set the proxyURL, are you finished it?

**Comment by stormeyes** [comment]
same

**Comment by ashish111333** [comment]
I have not tried it just wanted to ask if we can provide our own  Base URL for Open Ai client. @wcu1117

**Comment by jeremylazarus** [comment]
Try this. I'm using a man-in-the-middle proxy to view my requests with this:
```
	// client := openai.NewClient(apiKey) // Default client
	// Custom client config
	config := openai.DefaultConfig(apiKey)
	config.BaseURL = "http://localhost:8500/v1"
	client := openai.NewClientWithConfig(config)
```

**Comment by wcu1117** [comment]
> Try this. I'm using a man-in-the-middle proxy to view my requests with this:
> 
> ```
> 	// client := openai.NewClient(apiKey) // Default client
> 	// Custom client config
> 	config := openai.DefaultConfig(apiKey)
> 	config.BaseURL = "http://localhost:8500/v1"
> 	client := openai.NewClientWithConfig(config)
> ```

Well, it works! But why can't I set the proxy like this?
`transport := &http.Transport{
		Proxy: http.ProxyURL(proxy),
	}
	//config.BaseURL = proxyUrl
	config.HTTPClient = &http.Client{
		Transport: transport,
	}
client := openai.NewClientWithConfig(config)`
